@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section ewram_data,"aw"
	.type	 sLinkSendTaskId,object
	.size	 sLinkSendTaskId,1
sLinkSendTaskId:
	.byte	0x0
	.type	 sLinkReceiveTaskId,object
	.size	 sLinkReceiveTaskId,1
sLinkReceiveTaskId:
	.byte	0x0
	.type	 sUnknown_02022D0A,object
	.size	 sUnknown_02022D0A,1
sUnknown_02022D0A:
	.byte	0x0
	.globl	gUnknown_02022D0C
	.align	2, 0
	.type	 gUnknown_02022D0C,object
	.size	 gUnknown_02022D0C,4
gUnknown_02022D0C:
	.space	4
	.type	 sBattleBuffersTransferData,object
	.size	 sBattleBuffersTransferData,256
sBattleBuffersTransferData:
	.space	256
.text
	.align	2, 0
	.globl	HandleLinkBattleSetup
	.type	 HandleLinkBattleSetup,function
	.thumb_func
HandleLinkBattleSetup:
	push	{lr}
	ldr	r0, .L6
	ldr	r0, [r0]
	mov	r1, #0x2
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L3	@cond_branch
	ldr	r0, .L6+0x4
	ldrb	r0, [r0]
	cmp	r0, #0
	beq	.L4	@cond_branch
	bl	SetWirelessCommType1
.L4:
	ldr	r0, .L6+0x8
	ldrb	r0, [r0]
	cmp	r0, #0
	bne	.L5	@cond_branch
	bl	OpenLink
.L5:
	ldr	r0, .L6+0xc
	mov	r1, #0x0
	bl	CreateTask
	bl	CreateTasksForSendRecvLinkBuffers
.L3:
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	gBattleTypeFlags
	.word	gWirelessCommType
	.word	gReceivedRemoteLinkPlayers
	.word	Task_WaitForLinkPlayerConnection
.Lfe1:
	.size	 HandleLinkBattleSetup,.Lfe1-HandleLinkBattleSetup
	.align	2, 0
	.globl	SetUpBattleVarsAndBirchZigzagoon
	.type	 SetUpBattleVarsAndBirchZigzagoon,function
	.thumb_func
SetUpBattleVarsAndBirchZigzagoon:
	push	{r4, r5, r6, r7, lr}
	add	sp, sp, #-0x18
	ldr	r0, .L15
	ldr	r1, .L15+0x4
	str	r1, [r0]
	mov	r0, #0x0
	str	r0, [sp, #0x14]
	mov	r1, #0x0
	ldr	r7, .L15+0x8
	ldr	r6, .L15+0xc
	mov	r2, #0x0
	ldr	r5, .L15+0x10
	ldr	r4, .L15+0x14
	ldr	r3, .L15+0x18
.L12:
	lsl	r0, r1, #0x2
	add	r0, r0, r7
	str	r4, [r0]
	add	r1, r1, r3
	mov	r0, #0xff
	strb	r0, [r1]
	ldr	r0, [sp, #0x14]
	add	r0, r0, r6
	strb	r2, [r0]
	ldr	r0, [sp, #0x14]
	add	r0, r0, r5
	strb	r2, [r0]
	ldr	r0, [sp, #0x14]
	add	r0, r0, #0x1
	str	r0, [sp, #0x14]
	add	r1, r0, #0
	cmp	r1, #0x3
	ble	.L12	@cond_branch
	bl	HandleLinkBattleSetup
	ldr	r0, .L15+0x1c
	mov	r5, #0x0
	str	r5, [r0]
	bl	ClearBattleAnimationVars
	bl	ClearBattleMonForms
	bl	BattleAI_SetupItems
	bl	BattleAI_SetupFlags
	mov	r0, #0xf
	bl	BattleAI_SetupAIData
	ldr	r0, .L15+0x20
	ldr	r0, [r0]
	mov	r1, #0x10
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L14	@cond_branch
	bl	ZeroEnemyPartyMons
	ldr	r4, .L15+0x24
	ldr	r1, .L15+0x28
	str	r5, [sp]
	str	r5, [sp, #0x4]
	str	r5, [sp, #0x8]
	str	r5, [sp, #0xc]
	str	r5, [sp, #0x10]
	add	r0, r4, #0
	mov	r2, #0x2
	mov	r3, #0x20
	bl	CreateMon
	str	r5, [sp, #0x14]
	add	r0, r4, #0
	mov	r1, #0xc
	add	r2, sp, #0x14
	bl	SetMonData
.L14:
	ldr	r0, .L15+0x2c
	str	r5, [r0]
	ldr	r0, .L15+0x30
	strb	r5, [r0]
	add	sp, sp, #0x18
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L16:
	.align	2, 0
.L15:
	.word	gBattleMainFunc
	.word	nullsub_20
	.word	gBattlerControllerFuncs
	.word	gActionSelectionCursor
	.word	gMoveSelectionCursor
	.word	nullsub_21
	.word	gBattlerPositions
	.word	gBattleControllerExecFlags
	.word	gBattleTypeFlags
	.word	gEnemyParty
	.word	0x107
	.word	gUnknown_02022FF4
	.word	gUnknown_0202428C
.Lfe2:
	.size	 SetUpBattleVarsAndBirchZigzagoon,.Lfe2-SetUpBattleVarsAndBirchZigzagoon
	.align	2, 0
	.globl	sub_8032768
	.type	 sub_8032768,function
	.thumb_func
sub_8032768:
	push	{r4, r5, lr}
	ldr	r0, .L39
	ldr	r0, [r0]
	mov	r1, #0x80
	lsl	r1, r1, #0x11
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L18	@cond_branch
	mov	r0, #0x1
	bl	sub_8184DA4
	b	.L19
.L40:
	.align	2, 0
.L39:
	.word	gBattleTypeFlags
.L18:
	mov	r0, #0x2
	bl	sub_8184DA4
.L19:
	ldr	r4, .L41
	ldr	r0, [r4]
	mov	r1, #0x80
	lsl	r1, r1, #0x11
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L20	@cond_branch
	bl	RecordedBattle_SaveParties
.L20:
	ldr	r0, [r4]
	mov	r1, #0x2
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L21	@cond_branch
	bl	InitLinkBtlControllers
	b	.L22
.L42:
	.align	2, 0
.L41:
	.word	gBattleTypeFlags
.L21:
	bl	InitSinglePlayerBtlControllers
.L22:
	bl	SetBattlePartyIds
	ldr	r0, .L43
	ldr	r0, [r0]
	mov	r1, #0x40
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L23	@cond_branch
	mov	r4, #0x0
	ldr	r0, .L43+0x4
	ldrb	r1, [r0]
	cmp	r4, r1
	bge	.L23	@cond_branch
	add	r5, r0, #0
.L27:
	lsl	r0, r4, #0x18
	lsr	r0, r0, #0x18
	mov	r1, #0x0
	bl	BufferBattlePartyCurrentOrderBySide
	add	r4, r4, #0x1
	ldrb	r0, [r5]
	cmp	r4, r0
	blt	.L27	@cond_branch
.L23:
	mov	r4, #0x0
	ldr	r3, .L43+0x8
	mov	r2, #0xd0
	lsl	r2, r2, #0x1
	mov	r1, #0x0
.L32:
	ldr	r0, [r3]
	add	r0, r4, r0
	add	r0, r0, r2
	strb	r1, [r0]
	add	r4, r4, #0x1
	cmp	r4, #0x5f
	bls	.L32	@cond_branch
	mov	r4, #0x0
	ldr	r3, .L43+0x8
	mov	r2, #0x80
	lsl	r2, r2, #0x2
	mov	r1, #0x0
.L37:
	ldr	r0, [r3]
	add	r0, r4, r0
	add	r0, r0, r2
	strb	r1, [r0]
	add	r4, r4, #0x1
	cmp	r4, #0x67
	bls	.L37	@cond_branch
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L44:
	.align	2, 0
.L43:
	.word	gBattleTypeFlags
	.word	gBattlersCount
	.word	gBattleStruct
.Lfe3:
	.size	 sub_8032768,.Lfe3-sub_8032768
	.align	2, 0
	.type	 InitSinglePlayerBtlControllers,function
	.thumb_func
InitSinglePlayerBtlControllers:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr	r0, .L123
	ldr	r3, [r0]
	mov	r5, #0x80
	lsl	r5, r5, #0xf
	and	r5, r5, r3
	mov	ip, r0
	cmp	r5, #0
	beq	.L46	@cond_branch
	ldr	r1, .L123+0x4
	ldr	r0, .L123+0x8
	str	r0, [r1]
	mov	r4, #0x80
	lsl	r4, r4, #0x11
	and	r4, r4, r3
	cmp	r4, #0
	beq	.L47	@cond_branch
	ldr	r2, .L123+0xc
	ldr	r0, .L123+0x10
	str	r0, [r2]
	ldr	r1, .L123+0x14
	mov	r0, #0x0
	strb	r0, [r1]
	b	.L118
.L124:
	.align	2, 0
.L123:
	.word	gBattleTypeFlags
	.word	gBattleMainFunc
	.word	BeginBattleIntro
	.word	gBattlerControllerFuncs
	.word	SetControllerToRecordedPlayer
	.word	gBattlerPositions
.L47:
	ldr	r2, .L125
	ldr	r0, .L125+0x4
	str	r0, [r2]
	ldr	r1, .L125+0x8
	strb	r4, [r1]
.L118:
	ldr	r3, .L125+0xc
	str	r3, [r2, #0x4]
	mov	r0, #0x1
	strb	r0, [r1, #0x1]
	ldr	r0, .L125+0x10
	str	r0, [r2, #0x8]
	mov	r0, #0x2
	strb	r0, [r1, #0x2]
	str	r3, [r2, #0xc]
	mov	r0, #0x3
	strb	r0, [r1, #0x3]
	ldr	r1, .L125+0x14
	mov	r0, #0x4
	strb	r0, [r1]
	mov	r0, #0x0
	mov	r1, #0x0
	bl	BufferBattlePartyCurrentOrderBySide
	mov	r0, #0x1
	mov	r1, #0x0
	bl	BufferBattlePartyCurrentOrderBySide
	mov	r0, #0x2
	mov	r1, #0x1
	bl	BufferBattlePartyCurrentOrderBySide
	mov	r0, #0x3
	mov	r1, #0x1
	bl	BufferBattlePartyCurrentOrderBySide
	ldr	r2, .L125+0x18
	mov	r0, #0x0
	strh	r0, [r2]
	strh	r0, [r2, #0x2]
	ldr	r0, .L125+0x1c
	ldr	r0, [r0]
	mov	r1, #0x80
	lsl	r1, r1, #0xf
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L49	@cond_branch
	ldr	r0, .L125+0x20
	ldrh	r1, [r0]
	ldr	r0, .L125+0x24
	cmp	r1, r0
	bne	.L49	@cond_branch
	mov	r0, #0x3
	strh	r0, [r2, #0x4]
	mov	r0, #0x1
	strh	r0, [r2, #0x6]
	b	.L51
.L126:
	.align	2, 0
.L125:
	.word	gBattlerControllerFuncs
	.word	SetControllerToPlayer
	.word	gBattlerPositions
	.word	SetControllerToOpponent
	.word	SetControllerToPlayerPartner
	.word	gBattlersCount
	.word	gBattlerPartyIndexes
	.word	gBattleTypeFlags
	.word	gTrainerBattleOpponent_B
	.word	0xffff
.L49:
	ldr	r1, .L127
	mov	r0, #0x3
	strh	r0, [r1, #0x4]
	strh	r0, [r1, #0x6]
	b	.L51
.L128:
	.align	2, 0
.L127:
	.word	gBattlerPartyIndexes
.L46:
	mov	r7, #0x1
	add	r0, r3, #0
	and	r0, r0, r7
	cmp	r0, #0
	beq	.LCB441
	b	.L52	@long jump
.LCB441:
	ldr	r0, .L129
	ldr	r2, .L129+0x4
	str	r2, [r0]
	mov	r1, #0x80
	and	r1, r1, r3
	cmp	r1, #0
	beq	.L53	@cond_branch
	ldr	r1, .L129+0x8
	ldr	r0, .L129+0xc
	b	.L119
.L130:
	.align	2, 0
.L129:
	.word	gBattleMainFunc
	.word	BeginBattleIntro
	.word	gBattlerControllerFuncs
	.word	SetControllerToSafari
.L53:
	mov	r0, #0x80
	lsl	r0, r0, #0x2
	and	r3, r3, r0
	cmp	r3, #0
	beq	.L55	@cond_branch
	ldr	r1, .L131
	ldr	r0, .L131+0x4
	b	.L119
.L132:
	.align	2, 0
.L131:
	.word	gBattlerControllerFuncs
	.word	SetControllerToWally
.L55:
	ldr	r1, .L133
	ldr	r0, .L133+0x4
.L119:
	str	r0, [r1]
	mov	sl, r1
	ldr	r4, .L133+0x8
	mov	r0, #0x0
	mov	r9, r0
	mov	r1, r9
	strb	r1, [r4]
	mov	r5, sl
	ldr	r2, .L133+0xc
	mov	r8, r2
	str	r2, [r5, #0x4]
	mov	r6, #0x1
	strb	r6, [r4, #0x1]
	ldr	r2, .L133+0x10
	mov	r7, #0x2
	strb	r7, [r2]
	mov	r0, ip
	ldr	r3, [r0]
	mov	r0, #0x80
	lsl	r0, r0, #0x11
	and	r0, r0, r3
	cmp	r0, #0
	bne	.LCB509
	b	.L51	@long jump
.LCB509:
	mov	r1, #0x80
	lsl	r1, r1, #0x12
	and	r1, r1, r3
	cmp	r1, #0
	beq	.L58	@cond_branch
	mov	r1, #0x80
	lsl	r1, r1, #0x18
	and	r1, r1, r3
	cmp	r1, #0
	beq	.L59	@cond_branch
	ldr	r1, .L133+0x14
	ldr	r0, .L133+0x18
	str	r1, [r0]
	ldr	r0, .L133+0x1c
	str	r0, [r5]
	mov	r1, r9
	strb	r1, [r4]
	ldr	r0, .L133+0x20
	str	r0, [r5, #0x4]
	strb	r6, [r4, #0x1]
	strb	r7, [r2]
	b	.L51
.L134:
	.align	2, 0
.L133:
	.word	gBattlerControllerFuncs
	.word	SetControllerToPlayer
	.word	gBattlerPositions
	.word	SetControllerToOpponent
	.word	gBattlersCount
	.word	BeginBattleIntro
	.word	gBattleMainFunc
	.word	SetControllerToRecordedPlayer
	.word	SetControllerToRecordedOpponent
.L59:
	ldr	r0, .L135
	str	r0, [r5, #0x4]
	strb	r1, [r4, #0x1]
	ldr	r0, .L135+0x4
	str	r0, [r5]
	strb	r6, [r4]
	strb	r7, [r2]
	b	.L51
.L136:
	.align	2, 0
.L135:
	.word	SetControllerToRecordedPlayer
	.word	SetControllerToRecordedOpponent
.L58:
	ldr	r0, .L137
	mov	r2, sl
	str	r0, [r2]
	strb	r1, [r4]
	mov	r0, r8
	str	r0, [r2, #0x4]
	strb	r6, [r4, #0x1]
	b	.L51
.L138:
	.align	2, 0
.L137:
	.word	SetControllerToRecordedPlayer
.L52:
	ldr	r1, .L139
	ldr	r2, .L139+0x4
	str	r1, [r2]
	ldr	r2, .L139+0x8
	ldr	r0, .L139+0xc
	str	r0, [r2]
	ldr	r4, .L139+0x10
	strb	r5, [r4]
	ldr	r6, .L139+0x14
	str	r6, [r2, #0x4]
	strb	r7, [r4, #0x1]
	str	r0, [r2, #0x8]
	mov	r0, #0x2
	mov	ip, r0
	mov	r1, ip
	strb	r1, [r4, #0x2]
	str	r6, [r2, #0xc]
	mov	r0, #0x3
	mov	r8, r0
	mov	r1, r8
	strb	r1, [r4, #0x3]
	ldr	r0, .L139+0x18
	mov	sl, r0
	mov	r1, #0x4
	mov	r9, r1
	strb	r1, [r0]
	mov	r0, #0x80
	lsl	r0, r0, #0x11
	and	r0, r0, r3
	cmp	r0, #0
	bne	.LCB621
	b	.L51	@long jump
.LCB621:
	mov	r1, #0xa0
	lsl	r1, r1, #0x1
	add	r0, r3, #0
	and	r0, r0, r1
	cmp	r0, r1
	bne	.L64	@cond_branch
	ldr	r0, .L139
	ldr	r1, .L139+0x4
	str	r0, [r1]
	ldr	r0, .L139+0x1c
	str	r0, [r2]
	strb	r5, [r4]
	str	r6, [r2, #0x4]
	strb	r7, [r4, #0x1]
	str	r0, [r2, #0x8]
	mov	r0, ip
	strb	r0, [r4, #0x2]
	str	r6, [r2, #0xc]
	mov	r1, r8
	strb	r1, [r4, #0x3]
	mov	r0, r9
	mov	r2, sl
	strb	r0, [r2]
	mov	r0, #0x0
	mov	r1, #0x0
	bl	BufferBattlePartyCurrentOrderBySide
	mov	r0, #0x1
	mov	r1, #0x0
	bl	BufferBattlePartyCurrentOrderBySide
	mov	r0, #0x2
	mov	r1, #0x1
	bl	BufferBattlePartyCurrentOrderBySide
	mov	r0, #0x3
	mov	r1, #0x1
	bl	BufferBattlePartyCurrentOrderBySide
	ldr	r0, .L139+0x20
	strh	r5, [r0]
	strh	r5, [r0, #0x2]
	mov	r1, r8
	strh	r1, [r0, #0x4]
	strh	r1, [r0, #0x6]
	b	.L51
.L140:
	.align	2, 0
.L139:
	.word	BeginBattleIntro
	.word	gBattleMainFunc
	.word	gBattlerControllerFuncs
	.word	SetControllerToPlayer
	.word	gBattlerPositions
	.word	SetControllerToOpponent
	.word	gBattlersCount
	.word	SetControllerToRecordedPlayer
	.word	gBattlerPartyIndexes
.L64:
	mov	r5, #0x40
	and	r5, r5, r3
	cmp	r5, #0
	bne	.LCB685
	b	.L66	@long jump
.LCB685:
	ldr	r0, .L141
	ldrb	r5, [r0]
	mov	r0, #0x0
	mov	sl, r0
	ldr	r1, .L141+0x4
	mov	ip, r1
	add	r7, r4, #0
	mov	r8, r0
	ldr	r6, .L141+0x8
	mov	r4, #0x0
	mov	r2, #0x3
	mov	r9, r2
.L70:
	mov	r1, ip
	add	r0, r4, r1
	ldrh	r0, [r0, #0x18]
	cmp	r0, #0x2
	bgt	.L78	@cond_branch
	cmp	r0, #0x1
	bge	.L75	@cond_branch
	cmp	r0, #0
	beq	.L73	@cond_branch
	b	.L71
.L142:
	.align	2, 0
.L141:
	.word	gUnknown_0203C7B4
	.word	gLinkPlayers
	.word	gBattlerPartyIndexes
.L78:
	cmp	r0, #0x3
	bne	.L71	@cond_branch
.L73:
	ldr	r0, .L143
	add	r0, r4, r0
	ldrb	r0, [r0, #0x18]
	mov	r1, #0x0
	bl	BufferBattlePartyCurrentOrderBySide
	b	.L71
.L144:
	.align	2, 0
.L143:
	.word	gLinkPlayers
.L75:
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	mov	r1, #0x1
	bl	BufferBattlePartyCurrentOrderBySide
.L71:
	cmp	sl, r5
	bne	.L79	@cond_branch
	ldr	r0, .L145
	add	r3, r4, r0
	ldrh	r1, [r3, #0x18]
	lsl	r1, r1, #0x2
	ldr	r2, .L145+0x4
	add	r1, r1, r2
	ldr	r2, .L145+0x8
	str	r2, [r1]
	ldrh	r1, [r3, #0x18]
	mov	ip, r0
	cmp	r1, #0x2
	bgt	.L87	@cond_branch
	cmp	r1, #0x1
	bge	.L84	@cond_branch
	cmp	r1, #0
	beq	.L82	@cond_branch
	b	.L69
.L146:
	.align	2, 0
.L145:
	.word	gLinkPlayers
	.word	gBattlerControllerFuncs
	.word	SetControllerToRecordedPlayer
.L87:
	cmp	r1, #0x3
	bne	.L69	@cond_branch
.L82:
	mov	r1, ip
	add	r0, r4, r1
	ldrh	r1, [r0, #0x18]
	add	r1, r1, r7
	mov	r2, r8
	strb	r2, [r1]
	ldrh	r0, [r0, #0x18]
	b	.L120
.L84:
	add	r1, r1, r7
	mov	r0, #0x2
	strb	r0, [r1]
	ldrh	r0, [r3, #0x18]
	b	.L121
.L79:
	ldr	r2, .L147
	add	r0, r4, r2
	ldrh	r1, [r0, #0x18]
	mov	r3, #0x1
	add	r0, r3, #0
	and	r0, r0, r1
	mov	ip, r2
	cmp	r0, #0
	bne	.L117	@cond_branch
	lsl	r0, r5, #0x3
	sub	r0, r0, r5
	lsl	r0, r0, #0x2
	add	r0, r0, ip
	ldrh	r1, [r0, #0x18]
	add	r0, r3, #0
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L90	@cond_branch
	b	.L89
.L148:
	.align	2, 0
.L147:
	.word	gLinkPlayers
.L117:
	lsl	r0, r5, #0x3
	sub	r0, r0, r5
	lsl	r0, r0, #0x2
	add	r0, r0, ip
	ldrh	r1, [r0, #0x18]
	add	r0, r3, #0
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L89	@cond_branch
.L90:
	mov	r0, ip
	add	r2, r4, r0
	ldrh	r0, [r2, #0x18]
	lsl	r0, r0, #0x2
	ldr	r1, .L149
	add	r0, r0, r1
	ldr	r1, .L149+0x4
	str	r1, [r0]
	ldrh	r1, [r2, #0x18]
	cmp	r1, #0x2
	bgt	.L99	@cond_branch
	cmp	r1, #0x1
	bge	.L96	@cond_branch
	cmp	r1, #0
	beq	.L94	@cond_branch
	b	.L69
.L150:
	.align	2, 0
.L149:
	.word	gBattlerControllerFuncs
	.word	SetControllerToRecordedPlayer
.L99:
	cmp	r1, #0x3
	bne	.L69	@cond_branch
.L94:
	mov	r2, ip
	add	r0, r4, r2
	ldrh	r1, [r0, #0x18]
	add	r1, r1, r7
	mov	r2, r8
	strb	r2, [r1]
	ldrh	r0, [r0, #0x18]
	b	.L120
.L96:
	add	r1, r1, r7
	mov	r0, #0x2
	strb	r0, [r1]
	b	.L122
.L89:
	mov	r0, ip
	add	r2, r4, r0
	ldrh	r0, [r2, #0x18]
	lsl	r0, r0, #0x2
	ldr	r1, .L151
	add	r0, r0, r1
	ldr	r1, .L151+0x4
	str	r1, [r0]
	ldrh	r0, [r2, #0x18]
	cmp	r0, #0x2
	bgt	.L108	@cond_branch
	cmp	r0, #0x1
	bge	.L105	@cond_branch
	cmp	r0, #0
	beq	.L103	@cond_branch
	b	.L69
.L152:
	.align	2, 0
.L151:
	.word	gBattlerControllerFuncs
	.word	SetControllerToRecordedOpponent
.L108:
	cmp	r0, #0x3
	bne	.L69	@cond_branch
.L103:
	mov	r0, ip
	add	r2, r4, r0
	ldrh	r0, [r2, #0x18]
	add	r0, r0, r7
	mov	r1, #0x1
	strb	r1, [r0]
	ldrh	r0, [r2, #0x18]
.L120:
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	mov	r1, r8
	strh	r1, [r0]
	b	.L69
.L105:
	add	r0, r0, r7
	mov	r1, r9
	strb	r1, [r0]
.L122:
	ldrh	r0, [r2, #0x18]
.L121:
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	mov	r2, r9
	strh	r2, [r0]
.L69:
	add	r4, r4, #0x1c
	mov	r0, #0x1
	add	sl, sl, r0
	mov	r1, sl
	cmp	r1, #0x3
	bgt	.LCB975
	b	.L70	@long jump
.LCB975:
	b	.L51
.L66:
	mov	r1, #0x4
	and	r1, r1, r3
	cmp	r1, #0
	beq	.L111	@cond_branch
	ldr	r0, .L153
	str	r0, [r2]
	strb	r5, [r4]
	str	r0, [r2, #0x8]
	mov	r0, ip
	strb	r0, [r4, #0x2]
	mov	r0, #0x80
	lsl	r0, r0, #0x12
	and	r3, r3, r0
	cmp	r3, #0
	beq	.L112	@cond_branch
	ldr	r0, .L153+0x4
	str	r0, [r2, #0x4]
	strb	r7, [r4, #0x1]
	str	r0, [r2, #0xc]
	mov	r1, r8
	strb	r1, [r4, #0x3]
	b	.L51
.L154:
	.align	2, 0
.L153:
	.word	SetControllerToRecordedPlayer
	.word	SetControllerToRecordedOpponent
.L112:
	str	r6, [r2, #0x4]
	strb	r7, [r4, #0x1]
	str	r6, [r2, #0xc]
	mov	r2, r8
	strb	r2, [r4, #0x3]
	b	.L51
.L111:
	ldr	r0, .L155
	str	r0, [r2, #0x4]
	strb	r1, [r4, #0x1]
	str	r0, [r2, #0xc]
	mov	r0, ip
	strb	r0, [r4, #0x3]
	mov	r0, #0x80
	lsl	r0, r0, #0x12
	and	r3, r3, r0
	cmp	r3, #0
	beq	.L115	@cond_branch
	ldr	r0, .L155+0x4
	str	r0, [r2]
	strb	r7, [r4]
	str	r0, [r2, #0x8]
	mov	r1, r8
	strb	r1, [r4, #0x2]
	b	.L51
.L156:
	.align	2, 0
.L155:
	.word	SetControllerToRecordedPlayer
	.word	SetControllerToRecordedOpponent
.L115:
	str	r6, [r2]
	strb	r7, [r4]
	str	r6, [r2, #0x8]
	mov	r2, r8
	strb	r2, [r4, #0x2]
.L51:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe4:
	.size	 InitSinglePlayerBtlControllers,.Lfe4-InitSinglePlayerBtlControllers
	.align	2, 0
	.type	 InitLinkBtlControllers,function
	.thumb_func
InitLinkBtlControllers:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr	r4, .L221
	ldr	r1, [r4]
	mov	r5, #0x1
	add	r3, r1, #0
	and	r3, r3, r5
	cmp	r3, #0
	bne	.L158	@cond_branch
	mov	r4, #0x4
	and	r4, r4, r1
	cmp	r4, #0
	beq	.L159	@cond_branch
	ldr	r1, .L221+0x4
	ldr	r0, .L221+0x8
	str	r0, [r1]
	ldr	r2, .L221+0xc
	ldr	r0, .L221+0x10
	str	r0, [r2]
	ldr	r1, .L221+0x14
	strb	r3, [r1]
	ldr	r0, .L221+0x18
	str	r0, [r2, #0x4]
	strb	r5, [r1, #0x1]
	ldr	r1, .L221+0x1c
	mov	r0, #0x2
	b	.L215
.L222:
	.align	2, 0
.L221:
	.word	gBattleTypeFlags
	.word	gBattleMainFunc
	.word	BeginBattleIntro
	.word	gBattlerControllerFuncs
	.word	SetControllerToPlayer
	.word	gBattlerPositions
	.word	SetControllerToLinkOpponent
	.word	gBattlersCount
.L159:
	ldr	r2, .L223
	ldr	r0, .L223+0x4
	str	r0, [r2, #0x4]
	ldr	r1, .L223+0x8
	strb	r4, [r1, #0x1]
	ldr	r0, .L223+0xc
	str	r0, [r2]
	strb	r5, [r1]
	ldr	r1, .L223+0x10
	mov	r0, #0x2
	b	.L215
.L224:
	.align	2, 0
.L223:
	.word	gBattlerControllerFuncs
	.word	SetControllerToPlayer
	.word	gBattlerPositions
	.word	SetControllerToLinkOpponent
	.word	gBattlersCount
.L158:
	mov	r0, #0x41
	and	r0, r0, r1
	cmp	r0, #0x1
	bne	.L162	@cond_branch
	mov	r6, #0x4
	add	r3, r6, #0
	and	r3, r3, r1
	cmp	r3, #0
	beq	.L163	@cond_branch
	ldr	r1, .L225
	ldr	r0, .L225+0x4
	str	r0, [r1]
	ldr	r2, .L225+0x8
	ldr	r4, .L225+0xc
	str	r4, [r2]
	ldr	r1, .L225+0x10
	mov	r0, #0x0
	strb	r0, [r1]
	ldr	r3, .L225+0x14
	str	r3, [r2, #0x4]
	strb	r5, [r1, #0x1]
	str	r4, [r2, #0x8]
	mov	r0, #0x2
	strb	r0, [r1, #0x2]
	str	r3, [r2, #0xc]
	mov	r0, #0x3
	strb	r0, [r1, #0x3]
	b	.L216
.L226:
	.align	2, 0
.L225:
	.word	gBattleMainFunc
	.word	BeginBattleIntro
	.word	gBattlerControllerFuncs
	.word	SetControllerToPlayer
	.word	gBattlerPositions
	.word	SetControllerToLinkOpponent
.L163:
	ldr	r2, .L227
	ldr	r0, .L227+0x4
	str	r0, [r2, #0x4]
	ldr	r1, .L227+0x8
	strb	r3, [r1, #0x1]
	ldr	r3, .L227+0xc
	str	r3, [r2]
	strb	r5, [r1]
	str	r0, [r2, #0xc]
	mov	r0, #0x2
	strb	r0, [r1, #0x3]
	str	r3, [r2, #0x8]
	mov	r0, #0x3
	strb	r0, [r1, #0x2]
.L216:
	ldr	r0, .L227+0x10
	strb	r6, [r0]
	b	.L161
.L228:
	.align	2, 0
.L227:
	.word	gBattlerControllerFuncs
	.word	SetControllerToPlayer
	.word	gBattlerPositions
	.word	SetControllerToLinkOpponent
	.word	gBattlersCount
.L162:
	mov	r0, #0x80
	lsl	r0, r0, #0x1
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L166	@cond_branch
	mov	r4, #0x4
	add	r3, r4, #0
	and	r3, r3, r1
	cmp	r3, #0
	beq	.L167	@cond_branch
	ldr	r1, .L229
	ldr	r0, .L229+0x4
	str	r0, [r1]
	ldr	r2, .L229+0x8
	ldr	r0, .L229+0xc
	str	r0, [r2]
	ldr	r1, .L229+0x10
	mov	r0, #0x0
	strb	r0, [r1]
	ldr	r3, .L229+0x14
	str	r3, [r2, #0x4]
	strb	r5, [r1, #0x1]
	ldr	r0, .L229+0x18
	b	.L217
.L230:
	.align	2, 0
.L229:
	.word	gBattleMainFunc
	.word	BeginBattleIntro
	.word	gBattlerControllerFuncs
	.word	SetControllerToPlayer
	.word	gBattlerPositions
	.word	SetControllerToOpponent
	.word	SetControllerToLinkPartner
.L167:
	ldr	r2, .L231
	ldr	r0, .L231+0x4
	str	r0, [r2]
	ldr	r1, .L231+0x8
	strb	r3, [r1]
	ldr	r3, .L231+0xc
	str	r3, [r2, #0x4]
	strb	r5, [r1, #0x1]
	ldr	r0, .L231+0x10
.L217:
	str	r0, [r2, #0x8]
	mov	r0, #0x2
	strb	r0, [r1, #0x2]
	str	r3, [r2, #0xc]
	mov	r0, #0x3
	strb	r0, [r1, #0x3]
	ldr	r0, .L231+0x14
	strb	r4, [r0]
	mov	r0, #0x0
	mov	r1, #0x0
	bl	BufferBattlePartyCurrentOrderBySide
	mov	r0, #0x1
	mov	r1, #0x0
	bl	BufferBattlePartyCurrentOrderBySide
	mov	r0, #0x2
	mov	r1, #0x1
	bl	BufferBattlePartyCurrentOrderBySide
	mov	r0, #0x3
	mov	r1, #0x1
	bl	BufferBattlePartyCurrentOrderBySide
	ldr	r0, .L231+0x18
	mov	r1, #0x0
	strh	r1, [r0]
	strh	r1, [r0, #0x2]
	mov	r1, #0x3
	strh	r1, [r0, #0x4]
	strh	r1, [r0, #0x6]
	b	.L161
.L232:
	.align	2, 0
.L231:
	.word	gBattlerControllerFuncs
	.word	SetControllerToLinkPartner
	.word	gBattlerPositions
	.word	SetControllerToLinkOpponent
	.word	SetControllerToPlayer
	.word	gBattlersCount
	.word	gBattlerPartyIndexes
.L166:
	bl	GetMultiplayerId
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	ldr	r0, [r4]
	mov	r1, #0x4
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L170	@cond_branch
	ldr	r1, .L233
	ldr	r0, .L233+0x4
	str	r0, [r1]
.L170:
	mov	r0, #0x0
	mov	sl, r0
	ldr	r1, .L233+0x8
	mov	ip, r1
	ldr	r7, .L233+0xc
	mov	r8, r0
	ldr	r6, .L233+0x10
	mov	r4, #0x0
	mov	r2, #0x3
	mov	r9, r2
.L174:
	mov	r1, ip
	add	r0, r4, r1
	ldrh	r0, [r0, #0x18]
	cmp	r0, #0x2
	bgt	.L182	@cond_branch
	cmp	r0, #0x1
	bge	.L179	@cond_branch
	cmp	r0, #0
	beq	.L177	@cond_branch
	b	.L175
.L234:
	.align	2, 0
.L233:
	.word	gBattleMainFunc
	.word	BeginBattleIntro
	.word	gLinkPlayers
	.word	gBattlerPositions
	.word	gBattlerPartyIndexes
.L182:
	cmp	r0, #0x3
	bne	.L175	@cond_branch
.L177:
	ldr	r0, .L235
	add	r0, r4, r0
	ldrb	r0, [r0, #0x18]
	mov	r1, #0x0
	bl	BufferBattlePartyCurrentOrderBySide
	b	.L175
.L236:
	.align	2, 0
.L235:
	.word	gLinkPlayers
.L179:
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	mov	r1, #0x1
	bl	BufferBattlePartyCurrentOrderBySide
.L175:
	cmp	sl, r5
	bne	.L183	@cond_branch
	ldr	r0, .L237
	add	r3, r4, r0
	ldrh	r1, [r3, #0x18]
	lsl	r1, r1, #0x2
	ldr	r2, .L237+0x4
	add	r1, r1, r2
	ldr	r2, .L237+0x8
	str	r2, [r1]
	ldrh	r1, [r3, #0x18]
	mov	ip, r0
	cmp	r1, #0x2
	bgt	.L191	@cond_branch
	cmp	r1, #0x1
	bge	.L188	@cond_branch
	cmp	r1, #0
	beq	.L186	@cond_branch
	b	.L173
.L238:
	.align	2, 0
.L237:
	.word	gLinkPlayers
	.word	gBattlerControllerFuncs
	.word	SetControllerToPlayer
.L191:
	cmp	r1, #0x3
	bne	.L173	@cond_branch
.L186:
	mov	r1, ip
	add	r0, r4, r1
	ldrh	r1, [r0, #0x18]
	add	r1, r1, r7
	mov	r2, r8
	strb	r2, [r1]
	ldrh	r0, [r0, #0x18]
	b	.L218
.L188:
	add	r1, r1, r7
	mov	r0, #0x2
	strb	r0, [r1]
	ldrh	r0, [r3, #0x18]
	b	.L219
.L183:
	ldr	r2, .L239
	add	r0, r4, r2
	ldrh	r1, [r0, #0x18]
	mov	r3, #0x1
	add	r0, r3, #0
	and	r0, r0, r1
	mov	ip, r2
	cmp	r0, #0
	bne	.L214	@cond_branch
	lsl	r0, r5, #0x3
	sub	r0, r0, r5
	lsl	r0, r0, #0x2
	add	r0, r0, ip
	ldrh	r1, [r0, #0x18]
	add	r0, r3, #0
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L194	@cond_branch
	b	.L193
.L240:
	.align	2, 0
.L239:
	.word	gLinkPlayers
.L214:
	lsl	r0, r5, #0x3
	sub	r0, r0, r5
	lsl	r0, r0, #0x2
	add	r0, r0, ip
	ldrh	r1, [r0, #0x18]
	add	r0, r3, #0
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L193	@cond_branch
.L194:
	mov	r0, ip
	add	r2, r4, r0
	ldrh	r0, [r2, #0x18]
	lsl	r0, r0, #0x2
	ldr	r1, .L241
	add	r0, r0, r1
	ldr	r1, .L241+0x4
	str	r1, [r0]
	ldrh	r1, [r2, #0x18]
	cmp	r1, #0x2
	bgt	.L203	@cond_branch
	cmp	r1, #0x1
	bge	.L200	@cond_branch
	cmp	r1, #0
	beq	.L198	@cond_branch
	b	.L173
.L242:
	.align	2, 0
.L241:
	.word	gBattlerControllerFuncs
	.word	SetControllerToLinkPartner
.L203:
	cmp	r1, #0x3
	bne	.L173	@cond_branch
.L198:
	mov	r2, ip
	add	r0, r4, r2
	ldrh	r1, [r0, #0x18]
	add	r1, r1, r7
	mov	r2, r8
	strb	r2, [r1]
	ldrh	r0, [r0, #0x18]
	b	.L218
.L200:
	add	r1, r1, r7
	mov	r0, #0x2
	strb	r0, [r1]
	b	.L220
.L193:
	mov	r0, ip
	add	r2, r4, r0
	ldrh	r0, [r2, #0x18]
	lsl	r0, r0, #0x2
	ldr	r1, .L243
	add	r0, r0, r1
	ldr	r1, .L243+0x4
	str	r1, [r0]
	ldrh	r0, [r2, #0x18]
	cmp	r0, #0x2
	bgt	.L212	@cond_branch
	cmp	r0, #0x1
	bge	.L209	@cond_branch
	cmp	r0, #0
	beq	.L207	@cond_branch
	b	.L173
.L244:
	.align	2, 0
.L243:
	.word	gBattlerControllerFuncs
	.word	SetControllerToLinkOpponent
.L212:
	cmp	r0, #0x3
	bne	.L173	@cond_branch
.L207:
	mov	r0, ip
	add	r2, r4, r0
	ldrh	r0, [r2, #0x18]
	add	r0, r0, r7
	mov	r1, #0x1
	strb	r1, [r0]
	ldrh	r0, [r2, #0x18]
.L218:
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	mov	r1, r8
	strh	r1, [r0]
	b	.L173
.L209:
	add	r0, r0, r7
	mov	r1, r9
	strb	r1, [r0]
.L220:
	ldrh	r0, [r2, #0x18]
.L219:
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	mov	r2, r9
	strh	r2, [r0]
.L173:
	add	r4, r4, #0x1c
	mov	r0, #0x1
	add	sl, sl, r0
	mov	r1, sl
	cmp	r1, #0x3
	bgt	.LCB1607
	b	.L174	@long jump
.LCB1607:
	ldr	r1, .L245
	mov	r0, #0x4
.L215:
	strb	r0, [r1]
.L161:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L246:
	.align	2, 0
.L245:
	.word	gBattlersCount
.Lfe5:
	.size	 InitLinkBtlControllers,.Lfe5-InitLinkBtlControllers
	.align	2, 0
	.type	 SetBattlePartyIds,function
	.thumb_func
SetBattlePartyIds:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr	r0, .L273
	ldr	r0, [r0]
	mov	r1, #0x40
	and	r0, r0, r1
	cmp	r0, #0
	beq	.LCB1637
	b	.L248	@long jump
.LCB1637:
	mov	r0, #0x0
	mov	r8, r0
	b	.L270
.L274:
	.align	2, 0
.L273:
	.word	gBattleTypeFlags
.L252:
	mov	r5, #0x0
	mov	r0, #0x1
	add	r0, r0, r8
	mov	sl, r0
	ldr	r0, .L275
	add	r0, r0, r8
	mov	r9, r0
	mov	r0, r8
	lsl	r6, r0, #0x1
	mov	r7, #0x0
.L256:
	mov	r0, r8
	cmp	r0, #0x1
	bgt	.L257	@cond_branch
	mov	r0, r9
	ldrb	r1, [r0]
	mov	r0, #0x1
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L258	@cond_branch
	ldr	r0, .L275+0x4
	b	.L271
.L276:
	.align	2, 0
.L275:
	.word	gBattlerPositions
	.word	gPlayerParty
.L258:
	ldr	r0, .L277
.L271:
	add	r4, r7, r0
	add	r0, r4, #0
	mov	r1, #0x39
	bl	GetMonData
	cmp	r0, #0
	beq	.L255	@cond_branch
	add	r0, r4, #0
	mov	r1, #0x41
	bl	GetMonData
	cmp	r0, #0
	beq	.L255	@cond_branch
	add	r0, r4, #0
	mov	r1, #0x41
	bl	GetMonData
	ldr	r1, .L277+0x4
	cmp	r0, r1
	beq	.L255	@cond_branch
	add	r0, r4, #0
	mov	r1, #0x2d
	bl	GetMonData
	cmp	r0, #0
	bne	.L255	@cond_branch
	ldr	r0, .L277+0x8
	add	r0, r6, r0
	strh	r5, [r0]
	b	.L251
.L278:
	.align	2, 0
.L277:
	.word	gEnemyParty
	.word	0x4b7
	.word	gBattlerPartyIndexes
.L257:
	mov	r0, r9
	ldrb	r1, [r0]
	mov	r0, #0x1
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L263	@cond_branch
	ldr	r0, .L279
	add	r4, r7, r0
	add	r0, r4, #0
	mov	r1, #0x39
	bl	GetMonData
	cmp	r0, #0
	beq	.L255	@cond_branch
	add	r0, r4, #0
	mov	r1, #0xb
	b	.L272
.L280:
	.align	2, 0
.L279:
	.word	gPlayerParty
.L263:
	ldr	r0, .L281
	add	r4, r7, r0
	add	r0, r4, #0
	mov	r1, #0x39
	bl	GetMonData
	cmp	r0, #0
	beq	.L255	@cond_branch
	add	r0, r4, #0
	mov	r1, #0x41
.L272:
	bl	GetMonData
	cmp	r0, #0
	beq	.L255	@cond_branch
	add	r0, r4, #0
	mov	r1, #0x41
	bl	GetMonData
	ldr	r1, .L281+0x4
	cmp	r0, r1
	beq	.L255	@cond_branch
	add	r0, r4, #0
	mov	r1, #0x2d
	bl	GetMonData
	cmp	r0, #0
	bne	.L255	@cond_branch
	ldr	r1, .L281+0x8
	mov	r0, r8
	sub	r0, r0, #0x2
	lsl	r0, r0, #0x1
	add	r0, r0, r1
	ldrh	r0, [r0]
	cmp	r0, r5
	beq	.L255	@cond_branch
	add	r0, r6, r1
	strh	r5, [r0]
	b	.L251
.L282:
	.align	2, 0
.L281:
	.word	gEnemyParty
	.word	0x4b7
	.word	gBattlerPartyIndexes
.L255:
	add	r7, r7, #0x64
	add	r5, r5, #0x1
	cmp	r5, #0x5
	ble	.L256	@cond_branch
.L251:
	mov	r8, sl
.L270:
	ldr	r0, .L283
	ldrb	r0, [r0]
	cmp	r8, r0
	bge	.LCB1843
	b	.L252	@long jump
.LCB1843:
	ldr	r0, .L283+0x4
	ldr	r0, [r0]
	mov	r1, #0x80
	lsl	r1, r1, #0x8
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L248	@cond_branch
	ldr	r0, .L283+0x8
	mov	r1, #0x0
	strh	r1, [r0, #0x2]
	mov	r1, #0x3
	strh	r1, [r0, #0x6]
.L248:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L284:
	.align	2, 0
.L283:
	.word	gBattlersCount
	.word	gBattleTypeFlags
	.word	gBattlerPartyIndexes
.Lfe6:
	.size	 SetBattlePartyIds,.Lfe6-SetBattlePartyIds
	.align	2, 0
	.type	 PrepareBufferDataTransfer,function
	.thumb_func
PrepareBufferDataTransfer:
	push	{r4, r5, r6, r7, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r3, r0, #0x18
	add	r5, r3, #0
	lsl	r2, r2, #0x10
	lsr	r2, r2, #0x10
	ldr	r0, .L303
	ldr	r0, [r0]
	mov	r1, #0x2
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L286	@cond_branch
	add	r0, r3, #0
	add	r1, r2, #0
	add	r2, r4, #0
	bl	PrepareBufferDataTransferLink
	b	.L287
.L304:
	.align	2, 0
.L303:
	.word	gBattleTypeFlags
.L286:
	cmp	r5, #0
	beq	.L289	@cond_branch
	cmp	r5, #0x1
	beq	.L295	@cond_branch
	b	.L287
.L289:
	mov	r3, #0x0
	cmp	r3, r2
	bge	.L287	@cond_branch
	ldr	r6, .L305
	ldr	r5, .L305+0x4
.L293:
	ldr	r0, [r6]
	ldrb	r1, [r5]
	lsl	r1, r1, #0x9
	add	r1, r3, r1
	add	r0, r0, #0x20
	add	r0, r0, r1
	ldrb	r1, [r4]
	strb	r1, [r0]
	add	r4, r4, #0x1
	add	r3, r3, #0x1
	cmp	r3, r2
	blt	.L293	@cond_branch
	b	.L287
.L306:
	.align	2, 0
.L305:
	.word	gBattleResources
	.word	gActiveBattler
.L295:
	mov	r3, #0x0
	cmp	r3, r2
	bge	.L287	@cond_branch
	ldr	r7, .L307
	ldr	r6, .L307+0x4
	mov	r5, #0x82
	lsl	r5, r5, #0x4
.L299:
	ldr	r0, [r7]
	ldrb	r1, [r6]
	lsl	r1, r1, #0x9
	add	r1, r3, r1
	add	r0, r0, r5
	add	r0, r0, r1
	ldrb	r1, [r4]
	strb	r1, [r0]
	add	r4, r4, #0x1
	add	r3, r3, #0x1
	cmp	r3, r2
	blt	.L299	@cond_branch
.L287:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L308:
	.align	2, 0
.L307:
	.word	gBattleResources
	.word	gActiveBattler
.Lfe7:
	.size	 PrepareBufferDataTransfer,.Lfe7-PrepareBufferDataTransfer
	.align	2, 0
	.type	 CreateTasksForSendRecvLinkBuffers,function
	.thumb_func
CreateTasksForSendRecvLinkBuffers:
	push	{r4, r5, r6, lr}
	ldr	r0, .L310
	mov	r1, #0x0
	bl	CreateTask
	ldr	r2, .L310+0x4
	strb	r0, [r2]
	ldr	r5, .L310+0x8
	ldrb	r1, [r2]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	mov	r6, #0x0
	mov	r4, #0x0
	strh	r4, [r0, #0x1e]
	ldrb	r1, [r2]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	strh	r4, [r0, #0x20]
	ldrb	r1, [r2]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	strh	r4, [r0, #0x22]
	ldrb	r1, [r2]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	strh	r4, [r0, #0x24]
	ldrb	r1, [r2]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	strh	r4, [r0, #0x26]
	ldr	r0, .L310+0xc
	mov	r1, #0x0
	bl	CreateTask
	ldr	r2, .L310+0x10
	strb	r0, [r2]
	ldrb	r1, [r2]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	strh	r4, [r0, #0x20]
	ldrb	r1, [r2]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	strh	r4, [r0, #0x22]
	ldrb	r1, [r2]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	strh	r4, [r0, #0x24]
	ldrb	r1, [r2]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	strh	r4, [r0, #0x26]
	ldr	r0, .L310+0x14
	strb	r6, [r0]
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L311:
	.align	2, 0
.L310:
	.word	Task_HandleSendLinkBuffersData
	.word	sLinkSendTaskId
	.word	gTasks
	.word	Task_HandleCopyReceivedLinkBuffersData
	.word	sLinkReceiveTaskId
	.word	sUnknown_02022D0A
.Lfe8:
	.size	 CreateTasksForSendRecvLinkBuffers,.Lfe8-CreateTasksForSendRecvLinkBuffers
	.align	2, 0
	.globl	PrepareBufferDataTransferLink
	.type	 PrepareBufferDataTransferLink,function
	.thumb_func
PrepareBufferDataTransferLink:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	r9, r2
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	mov	ip, r1
	mov	r1, #0x3
	mov	r0, ip
	bic	r0, r0, r1
	add	r0, r0, #0x4
	mov	r8, r0
	ldr	r2, .L319
	ldr	r3, .L319+0x4
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r4, r0, r2
	mov	r1, #0x24
	ldrsh	r0, [r4, r1]
	add	r0, r0, r8
	add	r0, r0, #0x9
	mov	r1, #0x80
	lsl	r1, r1, #0x5
	add	r5, r2, #0
	cmp	r0, r1
	ble	.L313	@cond_branch
	ldrh	r0, [r4, #0x24]
	mov	r2, #0x0
	strh	r0, [r4, #0x20]
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	strh	r2, [r0, #0x24]
.L313:
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	mov	r2, #0x24
	ldrsh	r1, [r0, r2]
	ldr	r4, .L319+0x8
	ldr	r0, [r4]
	add	r0, r0, r1
	strb	r6, [r0]
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	mov	r7, #0x24
	ldrsh	r1, [r0, r7]
	ldr	r0, [r4]
	add	r1, r1, r0
	ldr	r0, .L319+0xc
	ldrb	r0, [r0]
	strb	r0, [r1, #0x1]
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	mov	r2, #0x24
	ldrsh	r1, [r0, r2]
	ldr	r0, [r4]
	add	r1, r1, r0
	ldr	r0, .L319+0x10
	ldrb	r0, [r0]
	strb	r0, [r1, #0x2]
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	mov	r7, #0x24
	ldrsh	r1, [r0, r7]
	ldr	r0, [r4]
	add	r1, r1, r0
	ldr	r0, .L319+0x14
	ldrb	r0, [r0]
	strb	r0, [r1, #0x3]
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	mov	r1, #0x24
	ldrsh	r0, [r0, r1]
	ldr	r1, [r4]
	add	r0, r0, r1
	mov	r2, r8
	strb	r2, [r0, #0x4]
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	mov	r7, #0x24
	ldrsh	r1, [r0, r7]
	ldr	r0, [r4]
	add	r1, r1, r0
	mov	r0, #0xff
	lsl	r0, r0, #0x8
	mov	r2, r8
	and	r0, r0, r2
	asr	r0, r0, #0x8
	strb	r0, [r1, #0x5]
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	mov	r7, #0x24
	ldrsh	r1, [r0, r7]
	ldr	r0, [r4]
	add	r1, r1, r0
	ldr	r0, .L319+0x18
	ldrb	r0, [r0]
	strb	r0, [r1, #0x6]
	ldrb	r1, [r3]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r5
	mov	r2, #0x24
	ldrsh	r1, [r0, r2]
	ldr	r0, [r4]
	add	r1, r1, r0
	ldr	r0, .L319+0x1c
	ldrb	r0, [r0]
	strb	r0, [r1, #0x7]
	mov	r2, #0x0
	cmp	r2, ip
	bge	.L315	@cond_branch
	mov	sl, r5
	add	r6, r3, #0
.L317:
	ldrb	r1, [r6]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, sl
	mov	r7, #0x24
	ldrsh	r1, [r0, r7]
	ldr	r0, [r4]
	add	r1, r2, r1
	add	r1, r1, r0
	mov	r7, r9
	add	r0, r7, r2
	ldrb	r0, [r0]
	strb	r0, [r1, #0x8]
	add	r2, r2, #0x1
	cmp	r2, ip
	blt	.L317	@cond_branch
.L315:
	ldrb	r0, [r3]
	lsl	r1, r0, #0x2
	add	r1, r1, r0
	lsl	r1, r1, #0x3
	add	r1, r1, r5
	ldrh	r0, [r1, #0x24]
	add	r0, r0, r8
	add	r0, r0, #0x8
	strh	r0, [r1, #0x24]
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L320:
	.align	2, 0
.L319:
	.word	gTasks
	.word	sLinkSendTaskId
	.word	gLinkBattleSendBuffer
	.word	gActiveBattler
	.word	gBattlerAttacker
	.word	gBattlerTarget
	.word	gAbsentBattlerFlags
	.word	gEffectBattler
.Lfe9:
	.size	 PrepareBufferDataTransferLink,.Lfe9-PrepareBufferDataTransferLink
	.align	2, 0
	.type	 Task_HandleSendLinkBuffersData,function
	.thumb_func
Task_HandleSendLinkBuffersData:
	push	{r4, r5, r6, r7, lr}
	lsl	r0, r0, #0x18
	lsr	r4, r0, #0x18
	ldr	r1, .L350
	lsl	r0, r4, #0x2
	add	r0, r0, r4
	lsl	r0, r0, #0x3
	add	r0, r0, r1
	mov	r2, #0x1e
	ldrsh	r0, [r0, r2]
	add	r7, r1, #0
	cmp	r0, #0x5
	bls	.LCB2289
	b	.L322	@long jump
.LCB2289:
	lsl	r0, r0, #0x2
	ldr	r1, .L350+0x4
	add	r0, r0, r1
	ldr	r0, [r0]
	mov	pc, r0
.L351:
	.align	2, 0
.L350:
	.word	gTasks
	.word	.L345
	.align	2, 0
	.align	2, 0
.L345:
	.word	.L323
	.word	.L324
	.word	.L326
	.word	.L336
	.word	.L341
	.word	.L343
.L323:
	lsl	r0, r4, #0x2
	add	r0, r0, r4
	lsl	r0, r0, #0x3
	add	r0, r0, r7
	mov	r1, #0x64
	strh	r1, [r0, #0x1c]
	b	.L347
.L324:
	lsl	r0, r4, #0x2
	add	r0, r0, r4
	lsl	r0, r0, #0x3
	add	r1, r0, r7
	ldrh	r0, [r1, #0x1c]
	sub	r0, r0, #0x1
	strh	r0, [r1, #0x1c]
	lsl	r0, r0, #0x10
	cmp	r0, #0
	beq	.LCB2331
	b	.L322	@long jump
.LCB2331:
	ldrh	r0, [r1, #0x1e]
	add	r0, r0, #0x1
	b	.L348
.L326:
	ldr	r0, .L352
	ldrb	r0, [r0]
	cmp	r0, #0
	beq	.L327	@cond_branch
	lsl	r0, r4, #0x2
	add	r0, r0, r4
	lsl	r0, r0, #0x3
	add	r0, r0, r7
.L347:
	ldrh	r1, [r0, #0x1e]
	add	r1, r1, #0x1
	strh	r1, [r0, #0x1e]
	b	.L322
.L353:
	.align	2, 0
.L352:
	.word	gWirelessCommType
.L327:
	ldr	r0, .L354
	ldr	r1, [r0]
	mov	r0, #0x80
	lsl	r0, r0, #0x1
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L329	@cond_branch
	mov	r5, #0x2
	b	.L330
.L355:
	.align	2, 0
.L354:
	.word	gBattleTypeFlags
.L329:
	mov	r0, #0x40
	and	r1, r1, r0
	mov	r0, #0x2
	cmp	r1, #0
	beq	.L331	@cond_branch
	mov	r0, #0x4
.L331:
	add	r5, r0, #0
.L330:
	bl	GetLinkPlayerCount_2
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	cmp	r0, r5
	bcs	.LCB2397
	b	.L322	@long jump
.LCB2397:
	bl	IsLinkMaster
	lsl	r0, r0, #0x18
	cmp	r0, #0
	beq	.L334	@cond_branch
	bl	CheckShouldAdvanceLinkState
	ldr	r0, .L356
	lsl	r1, r4, #0x2
	add	r1, r1, r4
	lsl	r1, r1, #0x3
	add	r1, r1, r0
	ldrh	r0, [r1, #0x1e]
	add	r0, r0, #0x1
	b	.L348
.L357:
	.align	2, 0
.L356:
	.word	gTasks
.L334:
	ldr	r0, .L358
	lsl	r1, r4, #0x2
	add	r1, r1, r4
	lsl	r1, r1, #0x3
	add	r1, r1, r0
	ldrh	r0, [r1, #0x1e]
	add	r0, r0, #0x1
	b	.L348
.L359:
	.align	2, 0
.L358:
	.word	gTasks
.L336:
	lsl	r1, r4, #0x2
	add	r0, r1, r4
	lsl	r0, r0, #0x3
	add	r2, r0, r7
	mov	r3, #0x26
	ldrsh	r5, [r2, r3]
	mov	r0, #0x24
	ldrsh	r6, [r2, r0]
	mov	ip, r6
	cmp	r5, ip
	beq	.L322	@cond_branch
	ldrh	r0, [r2, #0x22]
	mov	r6, #0x22
	ldrsh	r3, [r2, r6]
	cmp	r3, #0
	bne	.L338	@cond_branch
	cmp	r5, ip
	ble	.L339	@cond_branch
	mov	r6, #0x20
	ldrsh	r0, [r2, r6]
	cmp	r5, r0
	bne	.L339	@cond_branch
	strh	r3, [r2, #0x20]
	strh	r3, [r2, #0x26]
.L339:
	add	r4, r1, r4
	lsl	r4, r4, #0x3
	add	r4, r4, r7
	mov	r0, #0x26
	ldrsh	r1, [r4, r0]
	ldr	r5, .L360
	ldr	r0, [r5]
	add	r1, r1, r0
	ldrb	r0, [r1, #0x4]
	ldrb	r1, [r1, #0x5]
	lsl	r1, r1, #0x8
	orr	r0, r0, r1
	add	r0, r0, #0x8
	lsl	r0, r0, #0x10
	lsr	r6, r0, #0x10
	bl	bitmask_all_link_players_but_self
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	mov	r1, #0x26
	ldrsh	r2, [r4, r1]
	ldr	r1, [r5]
	add	r1, r1, r2
	add	r2, r6, #0
	bl	SendBlock
	ldrh	r0, [r4, #0x1e]
	add	r0, r0, #0x1
	strh	r0, [r4, #0x1e]
	b	.L322
.L361:
	.align	2, 0
.L360:
	.word	gLinkBattleSendBuffer
.L338:
	sub	r0, r0, #0x1
	strh	r0, [r2, #0x22]
	b	.L322
.L341:
	bl	IsLinkTaskFinished
	lsl	r0, r0, #0x18
	cmp	r0, #0
	beq	.L322	@cond_branch
	ldr	r0, .L362
	lsl	r1, r4, #0x2
	add	r1, r1, r4
	lsl	r1, r1, #0x3
	add	r1, r1, r0
	mov	r3, #0x26
	ldrsh	r2, [r1, r3]
	ldr	r0, .L362+0x4
	ldr	r0, [r0]
	add	r2, r2, r0
	ldrb	r0, [r2, #0x4]
	ldrb	r2, [r2, #0x5]
	lsl	r2, r2, #0x8
	mov	r3, #0x1
	strh	r3, [r1, #0x22]
	orr	r0, r0, r2
	ldrh	r6, [r1, #0x26]
	add	r0, r0, r6
	add	r0, r0, #0x8
	strh	r0, [r1, #0x26]
	b	.L349
.L363:
	.align	2, 0
.L362:
	.word	gTasks
	.word	gLinkBattleSendBuffer
.L343:
	lsl	r0, r4, #0x2
	add	r0, r0, r4
	lsl	r0, r0, #0x3
	add	r1, r0, r7
	ldrh	r0, [r1, #0x22]
	sub	r0, r0, #0x1
	strh	r0, [r1, #0x22]
	lsl	r0, r0, #0x10
	cmp	r0, #0
	bne	.L322	@cond_branch
	mov	r0, #0x1
	strh	r0, [r1, #0x22]
.L349:
	mov	r0, #0x3
.L348:
	strh	r0, [r1, #0x1e]
.L322:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe10:
	.size	 Task_HandleSendLinkBuffersData,.Lfe10-Task_HandleSendLinkBuffersData
	.align	2, 0
	.globl	sub_8033648
	.type	 sub_8033648,function
	.thumb_func
sub_8033648:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr	r0, .L378
	ldrb	r0, [r0]
	cmp	r0, #0
	beq	.L365	@cond_branch
	ldr	r0, .L378+0x4
	ldr	r0, [r0]
	mov	r1, #0x20
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L365	@cond_branch
	bl	DestroyTask_RfuIdle
	mov	r4, #0x0
	ldr	r0, .L378+0x8
	mov	sl, r0
	b	.L366
.L379:
	.align	2, 0
.L378:
	.word	gReceivedRemoteLinkPlayers
	.word	gBattleTypeFlags
	.word	gBlockRecvBuffer
.L369:
	bl	GetBlockReceivedStatus
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r2, .L380
	lsl	r1, r4, #0x2
	add	r1, r1, r2
	ldr	r1, [r1]
	and	r0, r0, r1
	add	r1, r4, #0x1
	mov	r9, r1
	cmp	r0, #0
	beq	.L368	@cond_branch
	add	r0, r4, #0
	bl	ResetBlockReceivedFlag
	lsl	r0, r4, #0x8
	mov	r4, sl
	add	r3, r0, r4
	ldr	r1, .L380+0x4
	add	r0, r0, r1
	ldrh	r6, [r0]
	ldr	r7, .L380+0x8
	ldr	r4, .L380+0xc
	mov	ip, r4
	ldrb	r1, [r4]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r2, r0, r7
	mov	r0, #0x24
	ldrsh	r1, [r2, r0]
	add	r0, r6, #0
	add	r0, r0, #0x9
	add	r1, r1, r0
	mov	r0, #0x80
	lsl	r0, r0, #0x5
	cmp	r1, r0
	ble	.L371	@cond_branch
	ldrh	r0, [r2, #0x24]
	strh	r0, [r2, #0x20]
	ldrb	r1, [r4]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r7
	mov	r1, #0x0
	strh	r1, [r0, #0x24]
.L371:
	ldr	r2, .L380+0x10
	mov	r4, ip
	ldrb	r1, [r4]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x3
	add	r0, r0, r7
	mov	r4, #0x24
	ldrsh	r1, [r0, r4]
	ldr	r0, [r2]
	add	r5, r0, r1
	add	r4, r3, #0
	mov	r2, #0x0
	add	r3, r6, #0
	add	r3, r3, #0x8
	mov	r8, r7
	mov	r7, ip
	cmp	r2, r3
	bge	.L373	@cond_branch
.L375:
	add	r0, r5, r2
	add	r1, r4, r2
	ldrb	r1, [r1]
	strb	r1, [r0]
	add	r2, r2, #0x1
	cmp	r2, r3
	blt	.L375	@cond_branch
.L373:
	ldrb	r0, [r7]
	lsl	r1, r0, #0x2
	add	r1, r1, r0
	lsl	r1, r1, #0x3
	add	r1, r1, r8
	ldrh	r0, [r1, #0x24]
	add	r0, r6, r0
	add	r0, r0, #0x8
	strh	r0, [r1, #0x24]
.L368:
	mov	r1, r9
	lsl	r0, r1, #0x18
	lsr	r4, r0, #0x18
.L366:
	bl	GetLinkPlayerCount
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	cmp	r4, r0
	bcc	.L369	@cond_branch
.L365:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L381:
	.align	2, 0
.L380:
	.word	gBitTable
	.word	gBlockRecvBuffer+0x4
	.word	gTasks
	.word	sLinkReceiveTaskId
	.word	gLinkBattleRecvBuffer
.Lfe11:
	.size	 sub_8033648,.Lfe11-sub_8033648
	.align	2, 0
	.type	 Task_HandleCopyReceivedLinkBuffersData,function
	.thumb_func
Task_HandleCopyReceivedLinkBuffersData:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	lsl	r0, r0, #0x18
	lsr	r7, r0, #0x18
	ldr	r1, .L394
	lsl	r0, r7, #0x2
	add	r0, r0, r7
	lsl	r0, r0, #0x3
	add	r3, r0, r1
	mov	r0, #0x26
	ldrsh	r2, [r3, r0]
	mov	r4, #0x24
	ldrsh	r0, [r3, r4]
	cmp	r2, r0
	bne	.LCB2766
	b	.L382	@long jump
.LCB2766:
	cmp	r2, r0
	ble	.L384	@cond_branch
	mov	r4, #0x20
	ldrsh	r0, [r3, r4]
	cmp	r2, r0
	bne	.L384	@cond_branch
	mov	r0, #0x0
	strh	r0, [r3, #0x20]
	strh	r0, [r3, #0x26]
.L384:
	lsl	r2, r7, #0x2
	add	r0, r2, r7
	lsl	r0, r0, #0x3
	add	r5, r0, r1
	mov	r0, #0x26
	ldrsh	r1, [r5, r0]
	ldr	r3, .L394+0x4
	mov	r8, r3
	ldr	r0, [r3]
	add	r3, r1, r0
	ldrb	r4, [r3, #0x1]
	ldrb	r6, [r3, #0x4]
	ldrb	r0, [r3, #0x5]
	lsl	r0, r0, #0x8
	orr	r6, r6, r0
	ldrb	r0, [r3]
	mov	r9, r2
	cmp	r0, #0x1
	beq	.L389	@cond_branch
	cmp	r0, #0x1
	bgt	.L393	@cond_branch
	cmp	r0, #0
	beq	.L386	@cond_branch
	b	.L385
.L395:
	.align	2, 0
.L394:
	.word	gTasks
	.word	gLinkBattleRecvBuffer
.L393:
	cmp	r0, #0x2
	beq	.L390	@cond_branch
	b	.L385
.L386:
	ldr	r2, .L396
	ldr	r1, .L396+0x4
	lsl	r0, r4, #0x2
	add	r0, r0, r1
	ldr	r1, [r2]
	ldr	r0, [r0]
	and	r1, r1, r0
	cmp	r1, #0
	bne	.L382	@cond_branch
	ldr	r0, .L396+0x8
	ldr	r1, [r0]
	lsl	r0, r4, #0x9
	add	r0, r0, r1
	add	r0, r0, #0x20
	add	r1, r3, #0
	add	r1, r1, #0x8
	add	r2, r6, #0
	bl	memcpy
	add	r0, r4, #0
	bl	sub_803F850
	ldr	r0, .L396+0xc
	ldr	r0, [r0]
	mov	r1, #0x4
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L385	@cond_branch
	ldr	r2, .L396+0x10
	mov	r4, #0x26
	ldrsh	r0, [r5, r4]
	mov	r3, r8
	ldr	r1, [r3]
	add	r0, r0, r1
	ldrb	r0, [r0, #0x2]
	strb	r0, [r2]
	ldr	r2, .L396+0x14
	mov	r4, #0x26
	ldrsh	r0, [r5, r4]
	add	r0, r0, r1
	ldrb	r0, [r0, #0x3]
	strb	r0, [r2]
	ldr	r2, .L396+0x18
	mov	r3, #0x26
	ldrsh	r0, [r5, r3]
	add	r0, r0, r1
	ldrb	r0, [r0, #0x6]
	strb	r0, [r2]
	ldr	r2, .L396+0x1c
	mov	r4, #0x26
	ldrsh	r0, [r5, r4]
	add	r0, r0, r1
	ldrb	r0, [r0, #0x7]
	strb	r0, [r2]
	b	.L385
.L397:
	.align	2, 0
.L396:
	.word	gBattleControllerExecFlags
	.word	gBitTable
	.word	gBattleResources
	.word	gBattleTypeFlags
	.word	gBattlerAttacker
	.word	gBattlerTarget
	.word	gAbsentBattlerFlags
	.word	gEffectBattler
.L389:
	ldr	r0, .L398
	ldr	r1, [r0]
	lsl	r0, r4, #0x9
	add	r0, r0, r1
	mov	r1, #0x82
	lsl	r1, r1, #0x4
	add	r0, r0, r1
	add	r1, r3, #0
	add	r1, r1, #0x8
	add	r2, r6, #0
	bl	memcpy
	b	.L385
.L399:
	.align	2, 0
.L398:
	.word	gBattleResources
.L390:
	ldrb	r2, [r3, #0x8]
	ldr	r3, .L400
	ldr	r1, .L400+0x4
	lsl	r0, r4, #0x2
	add	r0, r0, r1
	lsl	r2, r2, #0x2
	ldr	r1, [r0]
	lsl	r1, r1, r2
	ldr	r0, [r3]
	bic	r0, r0, r1
	str	r0, [r3]
.L385:
	ldr	r0, .L400+0x8
	mov	r2, r9
	add	r1, r2, r7
	lsl	r1, r1, #0x3
	add	r1, r1, r0
	ldrh	r0, [r1, #0x26]
	add	r0, r6, r0
	add	r0, r0, #0x8
	strh	r0, [r1, #0x26]
.L382:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L401:
	.align	2, 0
.L400:
	.word	gBattleControllerExecFlags
	.word	gBitTable
	.word	gTasks
.Lfe12:
	.size	 Task_HandleCopyReceivedLinkBuffersData,.Lfe12-Task_HandleCopyReceivedLinkBuffersData
	.align	2, 0
	.globl	BtlController_EmitGetMonData
	.type	 BtlController_EmitGetMonData,function
	.thumb_func
BtlController_EmitGetMonData:
	push	{r4, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L403
	mov	r3, #0x0
	strb	r3, [r1]
	strb	r4, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r3, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L404:
	.align	2, 0
.L403:
	.word	sBattleBuffersTransferData
.Lfe13:
	.size	 BtlController_EmitGetMonData,.Lfe13-BtlController_EmitGetMonData
	.align	2, 0
	.globl	BtlController_EmitGetRawMonData
	.type	 BtlController_EmitGetRawMonData,function
	.thumb_func
BtlController_EmitGetRawMonData:
	push	{r4, r5, lr}
	add	r5, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L406
	mov	r4, #0x0
	mov	r3, #0x1
	strb	r3, [r1]
	strb	r5, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r4, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L407:
	.align	2, 0
.L406:
	.word	sBattleBuffersTransferData
.Lfe14:
	.size	 BtlController_EmitGetRawMonData,.Lfe14-BtlController_EmitGetRawMonData
	.align	2, 0
	.globl	BtlController_EmitSetMonData
	.type	 BtlController_EmitSetMonData,function
	.thumb_func
BtlController_EmitSetMonData:
	push	{r4, r5, r6, lr}
	ldr	r4, [sp, #0x10]
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	lsl	r3, r3, #0x18
	lsr	r5, r3, #0x18
	ldr	r0, .L414
	mov	r3, #0x2
	strb	r3, [r0]
	strb	r1, [r0, #0x1]
	strb	r2, [r0, #0x2]
	add	r1, r0, #0
	cmp	r5, #0
	beq	.L410	@cond_branch
	add	r3, r1, #0x3
	add	r2, r5, #0
.L412:
	ldrb	r0, [r4]
	strb	r0, [r3]
	add	r4, r4, #0x1
	add	r3, r3, #0x1
	sub	r2, r2, #0x1
	cmp	r2, #0
	bne	.L412	@cond_branch
.L410:
	add	r2, r5, #0x3
	add	r0, r6, #0
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L415:
	.align	2, 0
.L414:
	.word	sBattleBuffersTransferData
.Lfe15:
	.size	 BtlController_EmitSetMonData,.Lfe15-BtlController_EmitSetMonData
	.align	2, 0
	.globl	BtlController_EmitSetRawMonData
	.type	 BtlController_EmitSetRawMonData,function
	.thumb_func
BtlController_EmitSetRawMonData:
	push	{r4, r5, r6, lr}
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	lsl	r2, r2, #0x18
	lsr	r4, r2, #0x18
	ldr	r0, .L422
	mov	r2, #0x3
	strb	r2, [r0]
	strb	r1, [r0, #0x1]
	strb	r4, [r0, #0x2]
	add	r5, r0, #0
	cmp	r4, #0
	beq	.L418	@cond_branch
	add	r1, r5, #0x3
	add	r2, r4, #0
.L420:
	ldrb	r0, [r3]
	strb	r0, [r1]
	add	r3, r3, #0x1
	add	r1, r1, #0x1
	sub	r2, r2, #0x1
	cmp	r2, #0
	bne	.L420	@cond_branch
.L418:
	add	r2, r4, #0x3
	add	r0, r6, #0
	add	r1, r5, #0
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L423:
	.align	2, 0
.L422:
	.word	sBattleBuffersTransferData
.Lfe16:
	.size	 BtlController_EmitSetRawMonData,.Lfe16-BtlController_EmitSetRawMonData
	.align	2, 0
	.globl	BtlController_EmitLoadMonSprite
	.type	 BtlController_EmitLoadMonSprite,function
	.thumb_func
BtlController_EmitLoadMonSprite:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L425
	mov	r2, #0x4
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L426:
	.align	2, 0
.L425:
	.word	sBattleBuffersTransferData
.Lfe17:
	.size	 BtlController_EmitLoadMonSprite,.Lfe17-BtlController_EmitLoadMonSprite
	.align	2, 0
	.globl	BtlController_EmitSwitchInAnim
	.type	 BtlController_EmitSwitchInAnim,function
	.thumb_func
BtlController_EmitSwitchInAnim:
	push	{r4, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L428
	mov	r3, #0x5
	strb	r3, [r1]
	strb	r4, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r3, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L429:
	.align	2, 0
.L428:
	.word	sBattleBuffersTransferData
.Lfe18:
	.size	 BtlController_EmitSwitchInAnim,.Lfe18-BtlController_EmitSwitchInAnim
	.align	2, 0
	.globl	BtlController_EmitReturnMonToBall
	.type	 BtlController_EmitReturnMonToBall,function
	.thumb_func
BtlController_EmitReturnMonToBall:
	push	{lr}
	add	r3, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L431
	mov	r2, #0x6
	strb	r2, [r1]
	strb	r3, [r1, #0x1]
	mov	r2, #0x2
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L432:
	.align	2, 0
.L431:
	.word	sBattleBuffersTransferData
.Lfe19:
	.size	 BtlController_EmitReturnMonToBall,.Lfe19-BtlController_EmitReturnMonToBall
	.align	2, 0
	.globl	BtlController_EmitDrawTrainerPic
	.type	 BtlController_EmitDrawTrainerPic,function
	.thumb_func
BtlController_EmitDrawTrainerPic:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L434
	mov	r2, #0x7
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L435:
	.align	2, 0
.L434:
	.word	sBattleBuffersTransferData
.Lfe20:
	.size	 BtlController_EmitDrawTrainerPic,.Lfe20-BtlController_EmitDrawTrainerPic
	.align	2, 0
	.globl	BtlController_EmitTrainerSlide
	.type	 BtlController_EmitTrainerSlide,function
	.thumb_func
BtlController_EmitTrainerSlide:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L437
	mov	r2, #0x8
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L438:
	.align	2, 0
.L437:
	.word	sBattleBuffersTransferData
.Lfe21:
	.size	 BtlController_EmitTrainerSlide,.Lfe21-BtlController_EmitTrainerSlide
	.align	2, 0
	.globl	BtlController_EmitTrainerSlideBack
	.type	 BtlController_EmitTrainerSlideBack,function
	.thumb_func
BtlController_EmitTrainerSlideBack:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L440
	mov	r2, #0x9
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L441:
	.align	2, 0
.L440:
	.word	sBattleBuffersTransferData
.Lfe22:
	.size	 BtlController_EmitTrainerSlideBack,.Lfe22-BtlController_EmitTrainerSlideBack
	.align	2, 0
	.globl	BtlController_EmitFaintAnimation
	.type	 BtlController_EmitFaintAnimation,function
	.thumb_func
BtlController_EmitFaintAnimation:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L443
	mov	r2, #0xa
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L444:
	.align	2, 0
.L443:
	.word	sBattleBuffersTransferData
.Lfe23:
	.size	 BtlController_EmitFaintAnimation,.Lfe23-BtlController_EmitFaintAnimation
	.align	2, 0
	.globl	BtlController_EmitPaletteFade
	.type	 BtlController_EmitPaletteFade,function
	.thumb_func
BtlController_EmitPaletteFade:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L446
	mov	r2, #0xb
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L447:
	.align	2, 0
.L446:
	.word	sBattleBuffersTransferData
.Lfe24:
	.size	 BtlController_EmitPaletteFade,.Lfe24-BtlController_EmitPaletteFade
	.align	2, 0
	.globl	BtlController_EmitSuccessBallThrowAnim
	.type	 BtlController_EmitSuccessBallThrowAnim,function
	.thumb_func
BtlController_EmitSuccessBallThrowAnim:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L449
	mov	r2, #0xc
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L450:
	.align	2, 0
.L449:
	.word	sBattleBuffersTransferData
.Lfe25:
	.size	 BtlController_EmitSuccessBallThrowAnim,.Lfe25-BtlController_EmitSuccessBallThrowAnim
	.align	2, 0
	.globl	BtlController_EmitBallThrowAnim
	.type	 BtlController_EmitBallThrowAnim,function
	.thumb_func
BtlController_EmitBallThrowAnim:
	push	{lr}
	add	r3, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L452
	mov	r2, #0xd
	strb	r2, [r1]
	strb	r3, [r1, #0x1]
	mov	r2, #0x2
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L453:
	.align	2, 0
.L452:
	.word	sBattleBuffersTransferData
.Lfe26:
	.size	 BtlController_EmitBallThrowAnim,.Lfe26-BtlController_EmitBallThrowAnim
	.align	2, 0
	.globl	BtlController_EmitPause
	.type	 BtlController_EmitPause,function
	.thumb_func
BtlController_EmitPause:
	push	{r4, r5, r6, lr}
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	lsl	r1, r1, #0x18
	lsr	r4, r1, #0x18
	ldr	r1, .L460
	mov	r0, #0xe
	strb	r0, [r1]
	strb	r4, [r1, #0x1]
	lsl	r0, r4, #0x1
	add	r0, r0, r4
	add	r5, r1, #0
	cmp	r0, #0
	beq	.L456	@cond_branch
	add	r1, r5, #0x2
	add	r3, r0, #0
.L458:
	ldrb	r0, [r2]
	strb	r0, [r1]
	add	r2, r2, #0x1
	add	r1, r1, #0x1
	sub	r3, r3, #0x1
	cmp	r3, #0
	bne	.L458	@cond_branch
.L456:
	lsl	r2, r4, #0x1
	add	r2, r2, r4
	add	r2, r2, #0x2
	add	r0, r6, #0
	add	r1, r5, #0
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L461:
	.align	2, 0
.L460:
	.word	sBattleBuffersTransferData
.Lfe27:
	.size	 BtlController_EmitPause,.Lfe27-BtlController_EmitPause
	.align	2, 0
	.globl	BtlController_EmitMoveAnimation
	.type	 BtlController_EmitMoveAnimation,function
	.thumb_func
BtlController_EmitMoveAnimation:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r4, [sp, #0x18]
	ldr	r5, [sp, #0x1c]
	ldr	r6, [sp, #0x24]
	mov	ip, r6
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	mov	r8, r0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	lsl	r3, r3, #0x10
	lsr	r3, r3, #0x10
	ldr	r7, .L465
	mov	r0, #0xf
	strb	r0, [r7]
	strb	r1, [r7, #0x1]
	lsr	r1, r1, #0x8
	strb	r1, [r7, #0x2]
	strb	r2, [r7, #0x3]
	strb	r3, [r7, #0x4]
	mov	r6, #0xff
	lsl	r6, r6, #0x8
	lsr	r3, r3, #0x8
	strb	r3, [r7, #0x5]
	strb	r4, [r7, #0x6]
	add	r0, r4, #0
	and	r0, r0, r6
	asr	r0, r0, #0x8
	strb	r0, [r7, #0x7]
	mov	r0, #0xff
	lsl	r0, r0, #0x10
	and	r0, r0, r4
	asr	r0, r0, #0x10
	strb	r0, [r7, #0x8]
	lsr	r4, r4, #0x18
	strb	r4, [r7, #0x9]
	strb	r5, [r7, #0xa]
	mov	r0, ip
	strb	r0, [r7, #0xb]
	mov	r0, #0xd
	bl	IsAbilityOnField
	cmp	r0, #0
	bne	.L463	@cond_branch
	mov	r0, #0x4c
	bl	IsAbilityOnField
	cmp	r0, #0
	bne	.L463	@cond_branch
	ldr	r0, .L465+0x4
	ldrh	r0, [r0]
	strb	r0, [r7, #0xc]
	and	r6, r6, r0
	lsr	r0, r6, #0x8
	strb	r0, [r7, #0xd]
	add	r4, r7, #0
	b	.L464
.L466:
	.align	2, 0
.L465:
	.word	sBattleBuffersTransferData
	.word	gBattleWeather
.L463:
	ldr	r0, .L467
	mov	r1, #0x0
	strb	r1, [r0, #0xc]
	strb	r1, [r0, #0xd]
	add	r4, r0, #0
.L464:
	mov	r0, #0x0
	strb	r0, [r4, #0xe]
	strb	r0, [r4, #0xf]
	add	r0, r4, #0
	add	r0, r0, #0x10
	ldr	r1, [sp, #0x20]
	mov	r2, #0x28
	bl	memcpy
	mov	r0, r8
	add	r1, r4, #0
	mov	r2, #0x38
	bl	PrepareBufferDataTransfer
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L468:
	.align	2, 0
.L467:
	.word	sBattleBuffersTransferData
.Lfe28:
	.size	 BtlController_EmitMoveAnimation,.Lfe28-BtlController_EmitMoveAnimation
	.align	2, 0
	.globl	BtlController_EmitPrintString
	.type	 BtlController_EmitPrintString,function
	.thumb_func
BtlController_EmitPrintString:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	mov	sl, r0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r2, .L480
	mov	r0, #0x10
	strb	r0, [r2]
	ldr	r0, .L480+0x4
	ldrb	r0, [r0]
	strb	r0, [r2, #0x1]
	strb	r1, [r2, #0x2]
	lsr	r1, r1, #0x8
	strb	r1, [r2, #0x3]
	add	r5, r2, #0x4
	ldr	r4, .L480+0x8
	ldrh	r0, [r4]
	strh	r0, [r2, #0x4]
	ldr	r0, .L480+0xc
	ldrh	r0, [r0]
	strh	r0, [r5, #0x2]
	ldr	r0, .L480+0x10
	ldrh	r0, [r0]
	strh	r0, [r5, #0x4]
	ldr	r0, .L480+0x14
	ldrh	r0, [r0]
	strh	r0, [r5, #0x6]
	ldr	r0, .L480+0x18
	ldrb	r0, [r0, #0x17]
	strb	r0, [r5, #0x8]
	ldr	r0, .L480+0x1c
	ldr	r0, [r0]
	add	r1, r0, #0
	add	r1, r1, #0x52
	ldrb	r1, [r1]
	strb	r1, [r5, #0x9]
	add	r0, r0, #0xa6
	ldrb	r0, [r0]
	strb	r0, [r5, #0xa]
	ldr	r0, .L480+0x20
	ldrb	r0, [r0]
	strb	r0, [r5, #0xb]
	ldr	r3, .L480+0x24
	ldrh	r1, [r4]
	lsl	r0, r1, #0x2
	add	r0, r0, r1
	lsl	r0, r0, #0x2
	add	r0, r0, r3
	ldrb	r0, [r0, #0x3]
	strb	r0, [r5, #0xc]
	mov	r9, r2
	ldr	r0, .L480+0x28
	mov	r8, r0
	ldr	r4, .L480+0x2c
	mov	r1, r9
	add	r1, r1, #0x12
	mov	r3, #0x3
.L473:
	ldrh	r0, [r4, #0x20]
	strh	r0, [r1]
	add	r4, r4, #0x5c
	add	r1, r1, #0x2
	sub	r3, r3, #0x1
	cmp	r3, #0
	bge	.L473	@cond_branch
	mov	r3, #0x0
	add	r6, r5, #0
	add	r6, r6, #0x16
	ldr	r0, .L480+0x30
	mov	ip, r0
	add	r4, r5, #0
	add	r4, r4, #0x28
	ldr	r7, .L480+0x34
	add	r2, r5, #0
	add	r2, r2, #0x3a
.L478:
	add	r1, r6, r3
	mov	r5, ip
	add	r0, r3, r5
	ldrb	r0, [r0]
	strb	r0, [r1]
	add	r1, r4, r3
	add	r0, r3, r7
	ldrb	r0, [r0]
	strb	r0, [r1]
	add	r1, r2, r3
	mov	r5, r8
	add	r0, r3, r5
	ldrb	r0, [r0]
	strb	r0, [r1]
	add	r3, r3, #0x1
	cmp	r3, #0x11
	ble	.L478	@cond_branch
	mov	r0, sl
	mov	r1, r9
	mov	r2, #0x50
	bl	PrepareBufferDataTransfer
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L481:
	.align	2, 0
.L480:
	.word	sBattleBuffersTransferData
	.word	gBattleOutcome
	.word	gCurrentMove
	.word	gChosenMove
	.word	gLastUsedItem
	.word	gLastUsedAbility
	.word	gBattleScripting
	.word	gBattleStruct
	.word	gPotentialItemEffectBattler
	.word	gBattleMoves
	.word	gBattleTextBuff3
	.word	gBattleMons
	.word	gBattleTextBuff1
	.word	gBattleTextBuff2
.Lfe29:
	.size	 BtlController_EmitPrintString,.Lfe29-BtlController_EmitPrintString
	.align	2, 0
	.globl	BtlController_EmitPrintSelectionString
	.type	 BtlController_EmitPrintSelectionString,function
	.thumb_func
BtlController_EmitPrintSelectionString:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	mov	sl, r0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r2, .L493
	mov	r0, #0x11
	strb	r0, [r2]
	strb	r0, [r2, #0x1]
	strb	r1, [r2, #0x2]
	lsr	r1, r1, #0x8
	strb	r1, [r2, #0x3]
	add	r4, r2, #0x4
	ldr	r0, .L493+0x4
	ldrh	r0, [r0]
	strh	r0, [r2, #0x4]
	ldr	r0, .L493+0x8
	ldrh	r0, [r0]
	strh	r0, [r4, #0x2]
	ldr	r0, .L493+0xc
	ldrh	r0, [r0]
	strh	r0, [r4, #0x4]
	ldr	r0, .L493+0x10
	ldrh	r0, [r0]
	strh	r0, [r4, #0x6]
	ldr	r0, .L493+0x14
	ldrb	r0, [r0, #0x17]
	strb	r0, [r4, #0x8]
	ldr	r0, .L493+0x18
	ldr	r0, [r0]
	add	r0, r0, #0x52
	ldrb	r0, [r0]
	strb	r0, [r4, #0x9]
	mov	r9, r2
	ldr	r0, .L493+0x1c
	mov	r8, r0
	ldr	r1, .L493+0x20
	mov	r2, #0x12
	add	r2, r2, r9
	mov	ip, r2
	mov	r3, #0x3
.L486:
	ldrh	r0, [r1, #0x20]
	mov	r2, ip
	strh	r0, [r2]
	add	r1, r1, #0x5c
	mov	r0, #0x2
	add	ip, ip, r0
	sub	r3, r3, #0x1
	cmp	r3, #0
	bge	.L486	@cond_branch
	mov	r3, #0x0
	add	r6, r4, #0
	add	r6, r6, #0x16
	ldr	r2, .L493+0x24
	mov	ip, r2
	add	r5, r4, #0
	add	r5, r5, #0x28
	ldr	r7, .L493+0x28
	add	r2, r4, #0
	add	r2, r2, #0x3a
.L491:
	add	r1, r6, r3
	mov	r4, ip
	add	r0, r3, r4
	ldrb	r0, [r0]
	strb	r0, [r1]
	add	r1, r5, r3
	add	r0, r3, r7
	ldrb	r0, [r0]
	strb	r0, [r1]
	add	r1, r2, r3
	mov	r4, r8
	add	r0, r3, r4
	ldrb	r0, [r0]
	strb	r0, [r1]
	add	r3, r3, #0x1
	cmp	r3, #0x11
	ble	.L491	@cond_branch
	mov	r0, sl
	mov	r1, r9
	mov	r2, #0x50
	bl	PrepareBufferDataTransfer
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L494:
	.align	2, 0
.L493:
	.word	sBattleBuffersTransferData
	.word	gCurrentMove
	.word	gChosenMove
	.word	gLastUsedItem
	.word	gLastUsedAbility
	.word	gBattleScripting
	.word	gBattleStruct
	.word	gBattleTextBuff3
	.word	gBattleMons
	.word	gBattleTextBuff1
	.word	gBattleTextBuff2
.Lfe30:
	.size	 BtlController_EmitPrintSelectionString,.Lfe30-BtlController_EmitPrintSelectionString
	.align	2, 0
	.globl	BtlController_EmitChooseAction
	.type	 BtlController_EmitChooseAction,function
	.thumb_func
BtlController_EmitChooseAction:
	push	{r4, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r2, r2, #0x10
	lsr	r2, r2, #0x10
	ldr	r1, .L496
	mov	r3, #0x12
	strb	r3, [r1]
	strb	r4, [r1, #0x1]
	strb	r2, [r1, #0x2]
	lsr	r2, r2, #0x8
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L497:
	.align	2, 0
.L496:
	.word	sBattleBuffersTransferData
.Lfe31:
	.size	 BtlController_EmitChooseAction,.Lfe31-BtlController_EmitChooseAction
	.align	2, 0
	.globl	BtlController_EmitUnknownYesNoBox
	.type	 BtlController_EmitUnknownYesNoBox,function
	.thumb_func
BtlController_EmitUnknownYesNoBox:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L499
	mov	r2, #0x13
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L500:
	.align	2, 0
.L499:
	.word	sBattleBuffersTransferData
.Lfe32:
	.size	 BtlController_EmitUnknownYesNoBox,.Lfe32-BtlController_EmitUnknownYesNoBox
	.align	2, 0
	.globl	BtlController_EmitChooseMove
	.type	 BtlController_EmitChooseMove,function
	.thumb_func
BtlController_EmitChooseMove:
	push	{r4, r5, r6, lr}
	add	r5, r3, #0
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	ldr	r3, .L507
	mov	r4, #0x0
	mov	r0, #0x14
	strb	r0, [r3]
	strb	r1, [r3, #0x1]
	strb	r2, [r3, #0x2]
	strb	r4, [r3, #0x3]
	mov	r2, #0x0
	add	r1, r3, #0
	add	r4, r1, #0x4
.L505:
	add	r0, r5, r2
	ldrb	r0, [r0]
	strb	r0, [r4]
	add	r4, r4, #0x1
	add	r2, r2, #0x1
	cmp	r2, #0x2f
	bls	.L505	@cond_branch
	add	r0, r6, #0
	mov	r2, #0x34
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L508:
	.align	2, 0
.L507:
	.word	sBattleBuffersTransferData
.Lfe33:
	.size	 BtlController_EmitChooseMove,.Lfe33-BtlController_EmitChooseMove
	.align	2, 0
	.globl	BtlController_EmitChooseItem
	.type	 BtlController_EmitChooseItem,function
	.thumb_func
BtlController_EmitChooseItem:
	push	{r4, r5, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	ldr	r1, .L515
	mov	r0, #0x15
	strb	r0, [r1]
	mov	r2, #0x0
	add	r3, r1, #0x1
.L513:
	add	r0, r4, r2
	ldrb	r0, [r0]
	strb	r0, [r3]
	add	r3, r3, #0x1
	add	r2, r2, #0x1
	cmp	r2, #0x2
	ble	.L513	@cond_branch
	add	r0, r5, #0
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L516:
	.align	2, 0
.L515:
	.word	sBattleBuffersTransferData
.Lfe34:
	.size	 BtlController_EmitChooseItem,.Lfe34-BtlController_EmitChooseItem
	.align	2, 0
	.globl	BtlController_EmitChoosePokemon
	.type	 BtlController_EmitChoosePokemon,function
	.thumb_func
BtlController_EmitChoosePokemon:
	push	{r4, r5, r6, lr}
	ldr	r6, [sp, #0x10]
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	ldr	r4, .L523
	mov	r0, #0x16
	strb	r0, [r4]
	strb	r1, [r4, #0x1]
	strb	r2, [r4, #0x2]
	strb	r3, [r4, #0x3]
	lsr	r3, r3, #0x8
	strb	r3, [r4, #0x7]
	mov	r2, #0x0
	add	r1, r4, #0
	add	r3, r1, #0x4
.L521:
	add	r0, r6, r2
	ldrb	r0, [r0]
	strb	r0, [r3]
	add	r3, r3, #0x1
	add	r2, r2, #0x1
	cmp	r2, #0x2
	ble	.L521	@cond_branch
	add	r0, r5, #0
	mov	r2, #0x8
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L524:
	.align	2, 0
.L523:
	.word	sBattleBuffersTransferData
.Lfe35:
	.size	 BtlController_EmitChoosePokemon,.Lfe35-BtlController_EmitChoosePokemon
	.align	2, 0
	.globl	BtlController_EmitCmd23
	.type	 BtlController_EmitCmd23,function
	.thumb_func
BtlController_EmitCmd23:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L526
	mov	r2, #0x17
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L527:
	.align	2, 0
.L526:
	.word	sBattleBuffersTransferData
.Lfe36:
	.size	 BtlController_EmitCmd23,.Lfe36-BtlController_EmitCmd23
	.align	2, 0
	.globl	BtlController_EmitHealthBarUpdate
	.type	 BtlController_EmitHealthBarUpdate,function
	.thumb_func
BtlController_EmitHealthBarUpdate:
	push	{r4, lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r3, .L529
	mov	r4, #0x0
	mov	r2, #0x18
	strb	r2, [r3]
	strb	r4, [r3, #0x1]
	strb	r1, [r3, #0x2]
	lsl	r1, r1, #0x10
	asr	r1, r1, #0x10
	mov	r2, #0xff
	lsl	r2, r2, #0x8
	and	r1, r1, r2
	asr	r1, r1, #0x8
	strb	r1, [r3, #0x3]
	add	r1, r3, #0
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L530:
	.align	2, 0
.L529:
	.word	sBattleBuffersTransferData
.Lfe37:
	.size	 BtlController_EmitHealthBarUpdate,.Lfe37-BtlController_EmitHealthBarUpdate
	.align	2, 0
	.globl	BtlController_EmitExpUpdate
	.type	 BtlController_EmitExpUpdate,function
	.thumb_func
BtlController_EmitExpUpdate:
	push	{r4, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r2, r2, #0x10
	lsr	r2, r2, #0x10
	ldr	r1, .L532
	mov	r3, #0x19
	strb	r3, [r1]
	strb	r4, [r1, #0x1]
	strb	r2, [r1, #0x2]
	lsl	r2, r2, #0x10
	asr	r2, r2, #0x10
	mov	r3, #0xff
	lsl	r3, r3, #0x8
	and	r2, r2, r3
	asr	r2, r2, #0x8
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L533:
	.align	2, 0
.L532:
	.word	sBattleBuffersTransferData
.Lfe38:
	.size	 BtlController_EmitExpUpdate,.Lfe38-BtlController_EmitExpUpdate
	.align	2, 0
	.globl	BtlController_EmitStatusIconUpdate
	.type	 BtlController_EmitStatusIconUpdate,function
	.thumb_func
BtlController_EmitStatusIconUpdate:
	push	{r4, r5, r6, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L535
	mov	r3, #0x1a
	strb	r3, [r1]
	strb	r4, [r1, #0x1]
	mov	r6, #0xff
	lsl	r6, r6, #0x8
	add	r3, r4, #0
	and	r3, r3, r6
	lsr	r3, r3, #0x8
	strb	r3, [r1, #0x2]
	mov	r5, #0xff
	lsl	r5, r5, #0x10
	add	r3, r4, #0
	and	r3, r3, r5
	lsr	r3, r3, #0x10
	strb	r3, [r1, #0x3]
	lsr	r4, r4, #0x18
	strb	r4, [r1, #0x4]
	strb	r2, [r1, #0x5]
	add	r3, r2, #0
	and	r3, r3, r6
	lsr	r3, r3, #0x8
	strb	r3, [r1, #0x6]
	add	r3, r2, #0
	and	r3, r3, r5
	lsr	r3, r3, #0x10
	strb	r3, [r1, #0x7]
	lsr	r2, r2, #0x18
	strb	r2, [r1, #0x8]
	mov	r2, #0x9
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L536:
	.align	2, 0
.L535:
	.word	sBattleBuffersTransferData
.Lfe39:
	.size	 BtlController_EmitStatusIconUpdate,.Lfe39-BtlController_EmitStatusIconUpdate
	.align	2, 0
	.globl	BtlController_EmitStatusAnimation
	.type	 BtlController_EmitStatusAnimation,function
	.thumb_func
BtlController_EmitStatusAnimation:
	push	{r4, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L538
	mov	r3, #0x1b
	strb	r3, [r1]
	strb	r4, [r1, #0x1]
	strb	r2, [r1, #0x2]
	mov	r3, #0xff
	lsl	r3, r3, #0x8
	and	r3, r3, r2
	lsr	r3, r3, #0x8
	strb	r3, [r1, #0x3]
	mov	r3, #0xff
	lsl	r3, r3, #0x10
	and	r3, r3, r2
	lsr	r3, r3, #0x10
	strb	r3, [r1, #0x4]
	lsr	r2, r2, #0x18
	strb	r2, [r1, #0x5]
	mov	r2, #0x6
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L539:
	.align	2, 0
.L538:
	.word	sBattleBuffersTransferData
.Lfe40:
	.size	 BtlController_EmitStatusAnimation,.Lfe40-BtlController_EmitStatusAnimation
	.align	2, 0
	.globl	BtlController_EmitStatusXor
	.type	 BtlController_EmitStatusXor,function
	.thumb_func
BtlController_EmitStatusXor:
	push	{lr}
	add	r3, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L541
	mov	r2, #0x1c
	strb	r2, [r1]
	strb	r3, [r1, #0x1]
	mov	r2, #0x2
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L542:
	.align	2, 0
.L541:
	.word	sBattleBuffersTransferData
.Lfe41:
	.size	 BtlController_EmitStatusXor,.Lfe41-BtlController_EmitStatusXor
	.align	2, 0
	.globl	BtlController_EmitDataTransfer
	.type	 BtlController_EmitDataTransfer,function
	.thumb_func
BtlController_EmitDataTransfer:
	push	{r4, r5, r6, lr}
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	lsl	r1, r1, #0x10
	lsr	r4, r1, #0x10
	ldr	r1, .L549
	mov	r0, #0x1d
	strb	r0, [r1]
	strb	r0, [r1, #0x1]
	strb	r4, [r1, #0x2]
	lsr	r0, r4, #0x8
	strb	r0, [r1, #0x3]
	add	r5, r1, #0
	cmp	r4, #0
	beq	.L545	@cond_branch
	add	r1, r5, #0x4
	add	r3, r4, #0
.L547:
	ldrb	r0, [r2]
	strb	r0, [r1]
	add	r2, r2, #0x1
	add	r1, r1, #0x1
	sub	r3, r3, #0x1
	cmp	r3, #0
	bne	.L547	@cond_branch
.L545:
	add	r2, r4, #0x4
	lsl	r2, r2, #0x10
	lsr	r2, r2, #0x10
	add	r0, r6, #0
	add	r1, r5, #0
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L550:
	.align	2, 0
.L549:
	.word	sBattleBuffersTransferData
.Lfe42:
	.size	 BtlController_EmitDataTransfer,.Lfe42-BtlController_EmitDataTransfer
	.align	2, 0
	.globl	BtlController_EmitDMA3Transfer
	.type	 BtlController_EmitDMA3Transfer,function
	.thumb_func
BtlController_EmitDMA3Transfer:
	push	{r4, r5, r6, lr}
	add	r4, r3, #0
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	lsl	r2, r2, #0x10
	lsr	r5, r2, #0x10
	ldr	r2, .L557
	mov	r0, #0x1e
	strb	r0, [r2]
	strb	r1, [r2, #0x1]
	mov	r3, #0xff
	lsl	r3, r3, #0x8
	add	r0, r1, #0
	and	r0, r0, r3
	lsr	r0, r0, #0x8
	strb	r0, [r2, #0x2]
	mov	r0, #0xff
	lsl	r0, r0, #0x10
	and	r0, r0, r1
	lsr	r0, r0, #0x10
	strb	r0, [r2, #0x3]
	lsr	r1, r1, #0x18
	strb	r1, [r2, #0x4]
	strb	r5, [r2, #0x5]
	add	r0, r5, #0
	and	r0, r0, r3
	lsr	r0, r0, #0x8
	strb	r0, [r2, #0x6]
	add	r1, r2, #0
	cmp	r5, #0
	beq	.L553	@cond_branch
	add	r3, r1, #0x7
	add	r2, r5, #0
.L555:
	ldrb	r0, [r4]
	strb	r0, [r3]
	add	r4, r4, #0x1
	add	r3, r3, #0x1
	sub	r2, r2, #0x1
	cmp	r2, #0
	bne	.L555	@cond_branch
.L553:
	add	r2, r5, #0x7
	lsl	r2, r2, #0x10
	lsr	r2, r2, #0x10
	add	r0, r6, #0
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L558:
	.align	2, 0
.L557:
	.word	sBattleBuffersTransferData
.Lfe43:
	.size	 BtlController_EmitDMA3Transfer,.Lfe43-BtlController_EmitDMA3Transfer
	.align	2, 0
	.globl	BtlController_EmitPlayBGM
	.type	 BtlController_EmitPlayBGM,function
	.thumb_func
BtlController_EmitPlayBGM:
	push	{r4, r5, r6, lr}
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	lsl	r1, r1, #0x10
	lsr	r4, r1, #0x10
	ldr	r1, .L565
	mov	r0, #0x1f
	strb	r0, [r1]
	strb	r4, [r1, #0x1]
	lsr	r0, r4, #0x8
	strb	r0, [r1, #0x2]
	add	r5, r1, #0
	cmp	r4, #0
	beq	.L561	@cond_branch
	add	r1, r5, #0x3
	add	r3, r4, #0
.L563:
	ldrb	r0, [r2]
	strb	r0, [r1]
	add	r2, r2, #0x1
	add	r1, r1, #0x1
	sub	r3, r3, #0x1
	cmp	r3, #0
	bne	.L563	@cond_branch
.L561:
	add	r2, r4, #0x3
	lsl	r2, r2, #0x10
	lsr	r2, r2, #0x10
	add	r0, r6, #0
	add	r1, r5, #0
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L566:
	.align	2, 0
.L565:
	.word	sBattleBuffersTransferData
.Lfe44:
	.size	 BtlController_EmitPlayBGM,.Lfe44-BtlController_EmitPlayBGM
	.align	2, 0
	.globl	BtlController_EmitCmd32
	.type	 BtlController_EmitCmd32,function
	.thumb_func
BtlController_EmitCmd32:
	push	{r4, r5, r6, lr}
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	lsl	r1, r1, #0x10
	lsr	r4, r1, #0x10
	ldr	r1, .L573
	mov	r0, #0x20
	strb	r0, [r1]
	strb	r4, [r1, #0x1]
	lsr	r0, r4, #0x8
	strb	r0, [r1, #0x2]
	add	r5, r1, #0
	cmp	r4, #0
	beq	.L569	@cond_branch
	add	r1, r5, #0x3
	add	r3, r4, #0
.L571:
	ldrb	r0, [r2]
	strb	r0, [r1]
	add	r2, r2, #0x1
	add	r1, r1, #0x1
	sub	r3, r3, #0x1
	cmp	r3, #0
	bne	.L571	@cond_branch
.L569:
	add	r2, r4, #0x3
	lsl	r2, r2, #0x10
	lsr	r2, r2, #0x10
	add	r0, r6, #0
	add	r1, r5, #0
	bl	PrepareBufferDataTransfer
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L574:
	.align	2, 0
.L573:
	.word	sBattleBuffersTransferData
.Lfe45:
	.size	 BtlController_EmitCmd32,.Lfe45-BtlController_EmitCmd32
	.align	2, 0
	.globl	BtlController_EmitTwoReturnValues
	.type	 BtlController_EmitTwoReturnValues,function
	.thumb_func
BtlController_EmitTwoReturnValues:
	push	{r4, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r2, r2, #0x10
	lsr	r2, r2, #0x10
	ldr	r1, .L576
	mov	r3, #0x21
	strb	r3, [r1]
	strb	r4, [r1, #0x1]
	strb	r2, [r1, #0x2]
	lsr	r2, r2, #0x8
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L577:
	.align	2, 0
.L576:
	.word	sBattleBuffersTransferData
.Lfe46:
	.size	 BtlController_EmitTwoReturnValues,.Lfe46-BtlController_EmitTwoReturnValues
	.align	2, 0
	.globl	BtlController_EmitChosenMonReturnValue
	.type	 BtlController_EmitChosenMonReturnValue,function
	.thumb_func
BtlController_EmitChosenMonReturnValue:
	push	{r4, r5, lr}
	add	r4, r2, #0
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	ldr	r2, .L584
	mov	r0, #0x22
	strb	r0, [r2]
	strb	r1, [r2, #0x1]
	mov	r3, #0x0
	add	r1, r2, #0x2
.L582:
	add	r0, r4, r3
	ldrb	r0, [r0]
	strb	r0, [r1]
	add	r1, r1, #0x1
	add	r3, r3, #0x1
	cmp	r3, #0x2
	ble	.L582	@cond_branch
	add	r0, r5, #0
	add	r1, r2, #0
	mov	r2, #0x5
	bl	PrepareBufferDataTransfer
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L585:
	.align	2, 0
.L584:
	.word	sBattleBuffersTransferData
.Lfe47:
	.size	 BtlController_EmitChosenMonReturnValue,.Lfe47-BtlController_EmitChosenMonReturnValue
	.align	2, 0
	.globl	BtlController_EmitOneReturnValue
	.type	 BtlController_EmitOneReturnValue,function
	.thumb_func
BtlController_EmitOneReturnValue:
	push	{r4, lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r3, .L587
	mov	r4, #0x0
	mov	r2, #0x23
	strb	r2, [r3]
	strb	r1, [r3, #0x1]
	lsr	r1, r1, #0x8
	strb	r1, [r3, #0x2]
	strb	r4, [r3, #0x3]
	add	r1, r3, #0
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L588:
	.align	2, 0
.L587:
	.word	sBattleBuffersTransferData
.Lfe48:
	.size	 BtlController_EmitOneReturnValue,.Lfe48-BtlController_EmitOneReturnValue
	.align	2, 0
	.globl	BtlController_EmitOneReturnValue_Duplicate
	.type	 BtlController_EmitOneReturnValue_Duplicate,function
	.thumb_func
BtlController_EmitOneReturnValue_Duplicate:
	push	{r4, lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r3, .L590
	mov	r4, #0x0
	mov	r2, #0x24
	strb	r2, [r3]
	strb	r1, [r3, #0x1]
	lsr	r1, r1, #0x8
	strb	r1, [r3, #0x2]
	strb	r4, [r3, #0x3]
	add	r1, r3, #0
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L591:
	.align	2, 0
.L590:
	.word	sBattleBuffersTransferData
.Lfe49:
	.size	 BtlController_EmitOneReturnValue_Duplicate,.Lfe49-BtlController_EmitOneReturnValue_Duplicate
	.align	2, 0
	.globl	BtlController_EmitCmd37
	.type	 BtlController_EmitCmd37,function
	.thumb_func
BtlController_EmitCmd37:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L593
	mov	r2, #0x25
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L594:
	.align	2, 0
.L593:
	.word	sBattleBuffersTransferData
.Lfe50:
	.size	 BtlController_EmitCmd37,.Lfe50-BtlController_EmitCmd37
	.align	2, 0
	.globl	BtlController_EmitCmd38
	.type	 BtlController_EmitCmd38,function
	.thumb_func
BtlController_EmitCmd38:
	push	{lr}
	add	r3, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L596
	mov	r2, #0x26
	strb	r2, [r1]
	strb	r3, [r1, #0x1]
	mov	r2, #0x2
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L597:
	.align	2, 0
.L596:
	.word	sBattleBuffersTransferData
.Lfe51:
	.size	 BtlController_EmitCmd38,.Lfe51-BtlController_EmitCmd38
	.align	2, 0
	.globl	BtlController_EmitCmd39
	.type	 BtlController_EmitCmd39,function
	.thumb_func
BtlController_EmitCmd39:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L599
	mov	r2, #0x27
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L600:
	.align	2, 0
.L599:
	.word	sBattleBuffersTransferData
.Lfe52:
	.size	 BtlController_EmitCmd39,.Lfe52-BtlController_EmitCmd39
	.align	2, 0
	.globl	BtlController_EmitCmd40
	.type	 BtlController_EmitCmd40,function
	.thumb_func
BtlController_EmitCmd40:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L602
	mov	r2, #0x28
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L603:
	.align	2, 0
.L602:
	.word	sBattleBuffersTransferData
.Lfe53:
	.size	 BtlController_EmitCmd40,.Lfe53-BtlController_EmitCmd40
	.align	2, 0
	.globl	BtlController_EmitHitAnimation
	.type	 BtlController_EmitHitAnimation,function
	.thumb_func
BtlController_EmitHitAnimation:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L605
	mov	r2, #0x29
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L606:
	.align	2, 0
.L605:
	.word	sBattleBuffersTransferData
.Lfe54:
	.size	 BtlController_EmitHitAnimation,.Lfe54-BtlController_EmitHitAnimation
	.align	2, 0
	.globl	BtlController_EmitCmd42
	.type	 BtlController_EmitCmd42,function
	.thumb_func
BtlController_EmitCmd42:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L608
	mov	r2, #0x2a
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L609:
	.align	2, 0
.L608:
	.word	sBattleBuffersTransferData
.Lfe55:
	.size	 BtlController_EmitCmd42,.Lfe55-BtlController_EmitCmd42
	.align	2, 0
	.globl	BtlController_EmitPlaySE
	.type	 BtlController_EmitPlaySE,function
	.thumb_func
BtlController_EmitPlaySE:
	push	{r4, lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r3, .L611
	mov	r4, #0x0
	mov	r2, #0x2b
	strb	r2, [r3]
	strb	r1, [r3, #0x1]
	lsr	r1, r1, #0x8
	strb	r1, [r3, #0x2]
	strb	r4, [r3, #0x3]
	add	r1, r3, #0
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L612:
	.align	2, 0
.L611:
	.word	sBattleBuffersTransferData
.Lfe56:
	.size	 BtlController_EmitPlaySE,.Lfe56-BtlController_EmitPlaySE
	.align	2, 0
	.globl	BtlController_EmitPlayFanfareOrBGM
	.type	 BtlController_EmitPlayFanfareOrBGM,function
	.thumb_func
BtlController_EmitPlayFanfareOrBGM:
	push	{r4, lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	ldr	r4, .L614
	mov	r3, #0x2c
	strb	r3, [r4]
	strb	r1, [r4, #0x1]
	lsr	r1, r1, #0x8
	strb	r1, [r4, #0x2]
	strb	r2, [r4, #0x3]
	add	r1, r4, #0
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L615:
	.align	2, 0
.L614:
	.word	sBattleBuffersTransferData
.Lfe57:
	.size	 BtlController_EmitPlayFanfareOrBGM,.Lfe57-BtlController_EmitPlayFanfareOrBGM
	.align	2, 0
	.globl	BtlController_EmitFaintingCry
	.type	 BtlController_EmitFaintingCry,function
	.thumb_func
BtlController_EmitFaintingCry:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L617
	mov	r2, #0x2d
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L618:
	.align	2, 0
.L617:
	.word	sBattleBuffersTransferData
.Lfe58:
	.size	 BtlController_EmitFaintingCry,.Lfe58-BtlController_EmitFaintingCry
	.align	2, 0
	.globl	BtlController_EmitIntroSlide
	.type	 BtlController_EmitIntroSlide,function
	.thumb_func
BtlController_EmitIntroSlide:
	push	{lr}
	add	r3, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L620
	mov	r2, #0x2e
	strb	r2, [r1]
	strb	r3, [r1, #0x1]
	mov	r2, #0x2
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L621:
	.align	2, 0
.L620:
	.word	sBattleBuffersTransferData
.Lfe59:
	.size	 BtlController_EmitIntroSlide,.Lfe59-BtlController_EmitIntroSlide
	.align	2, 0
	.globl	BtlController_EmitIntroTrainerBallThrow
	.type	 BtlController_EmitIntroTrainerBallThrow,function
	.thumb_func
BtlController_EmitIntroTrainerBallThrow:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L623
	mov	r2, #0x2f
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L624:
	.align	2, 0
.L623:
	.word	sBattleBuffersTransferData
.Lfe60:
	.size	 BtlController_EmitIntroTrainerBallThrow,.Lfe60-BtlController_EmitIntroTrainerBallThrow
	.align	2, 0
	.globl	BtlController_EmitDrawPartyStatusSummary
	.type	 BtlController_EmitDrawPartyStatusSummary,function
	.thumb_func
BtlController_EmitDrawPartyStatusSummary:
	push	{r4, r5, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	lsl	r2, r2, #0x18
	lsr	r2, r2, #0x18
	ldr	r1, .L631
	mov	r3, #0x30
	strb	r3, [r1]
	mov	r0, #0x7f
	and	r0, r0, r2
	strb	r0, [r1, #0x1]
	mov	r0, #0x80
	and	r0, r0, r2
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x1f
	strb	r0, [r1, #0x2]
	strb	r3, [r1, #0x3]
	mov	r2, #0x0
	add	r3, r1, #0x4
.L629:
	add	r0, r4, r2
	ldrb	r0, [r0]
	strb	r0, [r3]
	add	r3, r3, #0x1
	add	r2, r2, #0x1
	cmp	r2, #0x2f
	ble	.L629	@cond_branch
	add	r0, r5, #0
	mov	r2, #0x34
	bl	PrepareBufferDataTransfer
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L632:
	.align	2, 0
.L631:
	.word	sBattleBuffersTransferData
.Lfe61:
	.size	 BtlController_EmitDrawPartyStatusSummary,.Lfe61-BtlController_EmitDrawPartyStatusSummary
	.align	2, 0
	.globl	BtlController_EmitHidePartyStatusSummary
	.type	 BtlController_EmitHidePartyStatusSummary,function
	.thumb_func
BtlController_EmitHidePartyStatusSummary:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L634
	mov	r2, #0x31
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L635:
	.align	2, 0
.L634:
	.word	sBattleBuffersTransferData
.Lfe62:
	.size	 BtlController_EmitHidePartyStatusSummary,.Lfe62-BtlController_EmitHidePartyStatusSummary
	.align	2, 0
	.globl	BtlController_EmitEndBounceEffect
	.type	 BtlController_EmitEndBounceEffect,function
	.thumb_func
BtlController_EmitEndBounceEffect:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L637
	mov	r2, #0x32
	strb	r2, [r1]
	strb	r2, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L638:
	.align	2, 0
.L637:
	.word	sBattleBuffersTransferData
.Lfe63:
	.size	 BtlController_EmitEndBounceEffect,.Lfe63-BtlController_EmitEndBounceEffect
	.align	2, 0
	.globl	BtlController_EmitSpriteInvisibility
	.type	 BtlController_EmitSpriteInvisibility,function
	.thumb_func
BtlController_EmitSpriteInvisibility:
	push	{lr}
	add	r3, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L640
	mov	r2, #0x33
	strb	r2, [r1]
	strb	r3, [r1, #0x1]
	strb	r2, [r1, #0x2]
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L641:
	.align	2, 0
.L640:
	.word	sBattleBuffersTransferData
.Lfe64:
	.size	 BtlController_EmitSpriteInvisibility,.Lfe64-BtlController_EmitSpriteInvisibility
	.align	2, 0
	.globl	BtlController_EmitBattleAnimation
	.type	 BtlController_EmitBattleAnimation,function
	.thumb_func
BtlController_EmitBattleAnimation:
	push	{r4, lr}
	add	r4, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r2, r2, #0x10
	lsr	r2, r2, #0x10
	ldr	r1, .L643
	mov	r3, #0x34
	strb	r3, [r1]
	strb	r4, [r1, #0x1]
	strb	r2, [r1, #0x2]
	lsr	r2, r2, #0x8
	strb	r2, [r1, #0x3]
	mov	r2, #0x4
	bl	PrepareBufferDataTransfer
	pop	{r4}
	pop	{r0}
	bx	r0
.L644:
	.align	2, 0
.L643:
	.word	sBattleBuffersTransferData
.Lfe65:
	.size	 BtlController_EmitBattleAnimation,.Lfe65-BtlController_EmitBattleAnimation
	.align	2, 0
	.globl	BtlController_EmitLinkStandbyMsg
	.type	 BtlController_EmitLinkStandbyMsg,function
	.thumb_func
BtlController_EmitLinkStandbyMsg:
	push	{r4, r5, lr}
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	lsl	r2, r2, #0x18
	lsr	r2, r2, #0x18
	ldr	r4, .L648
	mov	r0, #0x35
	strb	r0, [r4]
	strb	r1, [r4, #0x1]
	cmp	r2, #0
	beq	.L646	@cond_branch
	add	r0, r4, #0x4
	bl	sub_81850DC
	strb	r0, [r4, #0x2]
	strb	r0, [r4, #0x3]
	b	.L647
.L649:
	.align	2, 0
.L648:
	.word	sBattleBuffersTransferData
.L646:
	strb	r2, [r4, #0x2]
	strb	r2, [r4, #0x3]
.L647:
	ldr	r1, .L650
	ldrb	r2, [r1, #0x2]
	add	r2, r2, #0x4
	add	r0, r5, #0
	bl	PrepareBufferDataTransfer
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L651:
	.align	2, 0
.L650:
	.word	sBattleBuffersTransferData
.Lfe66:
	.size	 BtlController_EmitLinkStandbyMsg,.Lfe66-BtlController_EmitLinkStandbyMsg
	.align	2, 0
	.globl	BtlController_EmitResetActionMoveSelection
	.type	 BtlController_EmitResetActionMoveSelection,function
	.thumb_func
BtlController_EmitResetActionMoveSelection:
	push	{lr}
	add	r3, r1, #0
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L653
	mov	r2, #0x36
	strb	r2, [r1]
	strb	r3, [r1, #0x1]
	mov	r2, #0x2
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L654:
	.align	2, 0
.L653:
	.word	sBattleBuffersTransferData
.Lfe67:
	.size	 BtlController_EmitResetActionMoveSelection,.Lfe67-BtlController_EmitResetActionMoveSelection
	.align	2, 0
	.globl	BtlController_EmitCmd55
	.type	 BtlController_EmitCmd55,function
	.thumb_func
BtlController_EmitCmd55:
	push	{r4, r5, lr}
	add	r5, r0, #0
	lsl	r5, r5, #0x18
	lsr	r5, r5, #0x18
	ldr	r4, .L656
	mov	r0, #0x37
	strb	r0, [r4]
	strb	r1, [r4, #0x1]
	ldr	r0, .L656+0x4
	ldr	r1, [r0]
	ldr	r0, .L656+0x8
	add	r1, r1, r0
	ldrb	r0, [r1]
	lsl	r0, r0, #0x1c
	lsr	r0, r0, #0x1f
	strb	r0, [r4, #0x2]
	ldrb	r0, [r1]
	lsl	r0, r0, #0x1c
	lsr	r0, r0, #0x1f
	strb	r0, [r4, #0x3]
	add	r0, r4, #0x6
	bl	sub_81850DC
	strb	r0, [r4, #0x4]
	strb	r0, [r4, #0x5]
	ldrb	r2, [r4, #0x4]
	add	r2, r2, #0x6
	add	r0, r5, #0
	add	r1, r4, #0
	bl	PrepareBufferDataTransfer
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L657:
	.align	2, 0
.L656:
	.word	sBattleBuffersTransferData
	.word	gSaveBlock2Ptr
	.word	0xc31
.Lfe68:
	.size	 BtlController_EmitCmd55,.Lfe68-BtlController_EmitCmd55
	.align	2, 0
	.globl	BtlController_EmitDebugMenu
	.type	 BtlController_EmitDebugMenu,function
	.thumb_func
BtlController_EmitDebugMenu:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L659
	mov	r2, #0x38
	strb	r2, [r1]
	mov	r2, #0x1
	bl	PrepareBufferDataTransfer
	pop	{r0}
	bx	r0
.L660:
	.align	2, 0
.L659:
	.word	sBattleBuffersTransferData
.Lfe69:
	.size	 BtlController_EmitDebugMenu,.Lfe69-BtlController_EmitDebugMenu
.text
	.align	2, 0

