@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section ewram_data,"aw"
	.type	 sFieldMessageBoxMode,object
	.size	 sFieldMessageBoxMode,1
sFieldMessageBoxMode:
	.byte	0x0
.text
	.align	2, 0
	.globl	InitFieldMessageBox
	.type	 InitFieldMessageBox,function
	.thumb_func
InitFieldMessageBox:
	ldr	r1, .L3
	mov	r0, #0x0
	strb	r0, [r1]
	ldr	r2, .L3+0x4
	ldrb	r1, [r2]
	mov	r0, #0x2
	neg	r0, r0
	and	r0, r0, r1
	mov	r1, #0x3
	neg	r1, r1
	and	r0, r0, r1
	sub	r1, r1, #0x2
	and	r0, r0, r1
	sub	r1, r1, #0x4
	and	r0, r0, r1
	strb	r0, [r2]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	sFieldMessageBoxMode
	.word	gTextFlags
.Lfe1:
	.size	 InitFieldMessageBox,.Lfe1-InitFieldMessageBox
	.align	2, 0
	.type	 Task_DrawFieldMessage,function
	.thumb_func
Task_DrawFieldMessage:
	push	{r4, r5, lr}
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	lsl	r0, r5, #0x2
	add	r0, r0, r5
	lsl	r0, r0, #0x3
	ldr	r1, .L15
	add	r4, r0, r1
	mov	r1, #0x8
	ldrsh	r0, [r4, r1]
	cmp	r0, #0x1
	beq	.L8	@cond_branch
	cmp	r0, #0x1
	bgt	.L13	@cond_branch
	cmp	r0, #0
	beq	.L7	@cond_branch
	b	.L6
.L16:
	.align	2, 0
.L15:
	.word	gTasks
.L13:
	cmp	r0, #0x2
	beq	.L9	@cond_branch
	b	.L6
.L7:
	bl	LoadMessageBoxAndBorderGfx
	b	.L14
.L8:
	mov	r0, #0x0
	mov	r1, #0x1
	bl	DrawDialogueFrame
.L14:
	ldrh	r0, [r4, #0x8]
	add	r0, r0, #0x1
	strh	r0, [r4, #0x8]
	b	.L6
.L9:
	bl	RunTextPrintersAndIsPrinter0Active
	lsl	r0, r0, #0x10
	lsr	r0, r0, #0x10
	cmp	r0, #0x1
	beq	.L6	@cond_branch
	ldr	r1, .L17
	mov	r0, #0x0
	strb	r0, [r1]
	add	r0, r5, #0
	bl	DestroyTask
.L6:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L18:
	.align	2, 0
.L17:
	.word	sFieldMessageBoxMode
.Lfe2:
	.size	 Task_DrawFieldMessage,.Lfe2-Task_DrawFieldMessage
	.align	2, 0
	.type	 CreateTask_DrawFieldMessage,function
	.thumb_func
CreateTask_DrawFieldMessage:
	push	{lr}
	ldr	r0, .L20
	mov	r1, #0x50
	bl	CreateTask
	pop	{r0}
	bx	r0
.L21:
	.align	2, 0
.L20:
	.word	Task_DrawFieldMessage
.Lfe3:
	.size	 CreateTask_DrawFieldMessage,.Lfe3-CreateTask_DrawFieldMessage
	.align	2, 0
	.type	 DestroyTask_DrawFieldMessage,function
	.thumb_func
DestroyTask_DrawFieldMessage:
	push	{lr}
	ldr	r0, .L24
	bl	FindTaskIdByFunc
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	cmp	r0, #0xff
	beq	.L23	@cond_branch
	bl	DestroyTask
.L23:
	pop	{r0}
	bx	r0
.L25:
	.align	2, 0
.L24:
	.word	Task_DrawFieldMessage
.Lfe4:
	.size	 DestroyTask_DrawFieldMessage,.Lfe4-DestroyTask_DrawFieldMessage
	.align	2, 0
	.globl	ShowFieldMessage
	.type	 ShowFieldMessage,function
	.thumb_func
ShowFieldMessage:
	push	{r4, lr}
	add	r1, r0, #0
	ldr	r4, .L29
	ldrb	r0, [r4]
	cmp	r0, #0
	bne	.L27	@cond_branch
	add	r0, r1, #0
	mov	r1, #0x1
	bl	ExpandStringAndStartDrawFieldMessage
	mov	r0, #0x2
	strb	r0, [r4]
	mov	r0, #0x1
	b	.L28
.L30:
	.align	2, 0
.L29:
	.word	sFieldMessageBoxMode
.L27:
	mov	r0, #0x0
.L28:
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe5:
	.size	 ShowFieldMessage,.Lfe5-ShowFieldMessage
	.align	2, 0
	.type	 Task_HidePokenavMessageWhenDone,function
	.thumb_func
Task_HidePokenavMessageWhenDone:
	push	{r4, lr}
	lsl	r0, r0, #0x18
	lsr	r4, r0, #0x18
	bl	IsMatchCallTaskActive
	add	r1, r0, #0
	cmp	r1, #0
	bne	.L32	@cond_branch
	ldr	r0, .L33
	strb	r1, [r0]
	add	r0, r4, #0
	bl	DestroyTask
.L32:
	pop	{r4}
	pop	{r0}
	bx	r0
.L34:
	.align	2, 0
.L33:
	.word	sFieldMessageBoxMode
.Lfe6:
	.size	 Task_HidePokenavMessageWhenDone,.Lfe6-Task_HidePokenavMessageWhenDone
	.align	2, 0
	.globl	ShowPokenavFieldMessage
	.type	 ShowPokenavFieldMessage,function
	.thumb_func
ShowPokenavFieldMessage:
	push	{r4, r5, lr}
	add	r4, r0, #0
	ldr	r5, .L38
	ldrb	r0, [r5]
	cmp	r0, #0
	bne	.L36	@cond_branch
	ldr	r0, .L38+0x4
	add	r1, r4, #0
	bl	StringExpandPlaceholders
	ldr	r0, .L38+0x8
	mov	r1, #0x0
	bl	CreateTask
	add	r0, r4, #0
	bl	StartMatchCallFromScript
	mov	r0, #0x2
	strb	r0, [r5]
	mov	r0, #0x1
	b	.L37
.L39:
	.align	2, 0
.L38:
	.word	sFieldMessageBoxMode
	.word	gStringVar4
	.word	Task_HidePokenavMessageWhenDone
.L36:
	mov	r0, #0x0
.L37:
	pop	{r4, r5}
	pop	{r1}
	bx	r1
.Lfe7:
	.size	 ShowPokenavFieldMessage,.Lfe7-ShowPokenavFieldMessage
	.align	2, 0
	.globl	ShowFieldAutoScrollMessage
	.type	 ShowFieldAutoScrollMessage,function
	.thumb_func
ShowFieldAutoScrollMessage:
	push	{lr}
	add	r1, r0, #0
	ldr	r2, .L43
	ldrb	r0, [r2]
	cmp	r0, #0
	bne	.L41	@cond_branch
	mov	r0, #0x3
	strb	r0, [r2]
	add	r0, r1, #0
	mov	r1, #0x0
	bl	ExpandStringAndStartDrawFieldMessage
	mov	r0, #0x1
	b	.L42
.L44:
	.align	2, 0
.L43:
	.word	sFieldMessageBoxMode
.L41:
	mov	r0, #0x0
.L42:
	pop	{r1}
	bx	r1
.Lfe8:
	.size	 ShowFieldAutoScrollMessage,.Lfe8-ShowFieldAutoScrollMessage
	.align	2, 0
	.type	 ForceShowFieldAutoScrollMessage,function
	.thumb_func
ForceShowFieldAutoScrollMessage:
	push	{lr}
	ldr	r2, .L46
	mov	r1, #0x3
	strb	r1, [r2]
	mov	r1, #0x1
	bl	ExpandStringAndStartDrawFieldMessage
	mov	r0, #0x1
	pop	{r1}
	bx	r1
.L47:
	.align	2, 0
.L46:
	.word	sFieldMessageBoxMode
.Lfe9:
	.size	 ForceShowFieldAutoScrollMessage,.Lfe9-ForceShowFieldAutoScrollMessage
	.align	2, 0
	.globl	ShowFieldMessageFromBuffer
	.type	 ShowFieldMessageFromBuffer,function
	.thumb_func
ShowFieldMessageFromBuffer:
	push	{lr}
	ldr	r1, .L51
	ldrb	r0, [r1]
	cmp	r0, #0
	bne	.L49	@cond_branch
	mov	r0, #0x2
	strb	r0, [r1]
	bl	StartDrawFieldMessage
	mov	r0, #0x1
	b	.L50
.L52:
	.align	2, 0
.L51:
	.word	sFieldMessageBoxMode
.L49:
	mov	r0, #0x0
.L50:
	pop	{r1}
	bx	r1
.Lfe10:
	.size	 ShowFieldMessageFromBuffer,.Lfe10-ShowFieldMessageFromBuffer
	.align	2, 0
	.type	 ExpandStringAndStartDrawFieldMessage,function
	.thumb_func
ExpandStringAndStartDrawFieldMessage:
	push	{r4, lr}
	add	r2, r0, #0
	add	r4, r1, #0
	ldr	r0, .L54
	add	r1, r2, #0
	bl	StringExpandPlaceholders
	lsl	r4, r4, #0x18
	lsr	r4, r4, #0x18
	add	r0, r4, #0
	bl	AddTextPrinterForMessage
	bl	CreateTask_DrawFieldMessage
	pop	{r4}
	pop	{r0}
	bx	r0
.L55:
	.align	2, 0
.L54:
	.word	gStringVar4
.Lfe11:
	.size	 ExpandStringAndStartDrawFieldMessage,.Lfe11-ExpandStringAndStartDrawFieldMessage
	.align	2, 0
	.type	 StartDrawFieldMessage,function
	.thumb_func
StartDrawFieldMessage:
	push	{lr}
	mov	r0, #0x1
	bl	AddTextPrinterForMessage
	bl	CreateTask_DrawFieldMessage
	pop	{r0}
	bx	r0
.Lfe12:
	.size	 StartDrawFieldMessage,.Lfe12-StartDrawFieldMessage
	.align	2, 0
	.globl	HideFieldMessageBox
	.type	 HideFieldMessageBox,function
	.thumb_func
HideFieldMessageBox:
	push	{lr}
	bl	DestroyTask_DrawFieldMessage
	mov	r0, #0x0
	mov	r1, #0x1
	bl	ClearDialogWindowAndFrame
	ldr	r1, .L58
	mov	r0, #0x0
	strb	r0, [r1]
	pop	{r0}
	bx	r0
.L59:
	.align	2, 0
.L58:
	.word	sFieldMessageBoxMode
.Lfe13:
	.size	 HideFieldMessageBox,.Lfe13-HideFieldMessageBox
	.align	2, 0
	.globl	GetFieldMessageBoxMode
	.type	 GetFieldMessageBoxMode,function
	.thumb_func
GetFieldMessageBoxMode:
	ldr	r0, .L61
	ldrb	r0, [r0]
	bx	lr
.L62:
	.align	2, 0
.L61:
	.word	sFieldMessageBoxMode
.Lfe14:
	.size	 GetFieldMessageBoxMode,.Lfe14-GetFieldMessageBoxMode
	.align	2, 0
	.globl	IsFieldMessageBoxHidden
	.type	 IsFieldMessageBoxHidden,function
	.thumb_func
IsFieldMessageBoxHidden:
	push	{lr}
	ldr	r0, .L66
	ldrb	r0, [r0]
	cmp	r0, #0
	beq	.L64	@cond_branch
	mov	r0, #0x0
	b	.L65
.L67:
	.align	2, 0
.L66:
	.word	sFieldMessageBoxMode
.L64:
	mov	r0, #0x1
.L65:
	pop	{r1}
	bx	r1
.Lfe15:
	.size	 IsFieldMessageBoxHidden,.Lfe15-IsFieldMessageBoxHidden
	.align	2, 0
	.type	 ReplaceFieldMessageWithFrame,function
	.thumb_func
ReplaceFieldMessageWithFrame:
	push	{lr}
	bl	DestroyTask_DrawFieldMessage
	mov	r0, #0x0
	mov	r1, #0x1
	bl	DrawStdWindowFrame
	ldr	r1, .L69
	mov	r0, #0x0
	strb	r0, [r1]
	pop	{r0}
	bx	r0
.L70:
	.align	2, 0
.L69:
	.word	sFieldMessageBoxMode
.Lfe16:
	.size	 ReplaceFieldMessageWithFrame,.Lfe16-ReplaceFieldMessageWithFrame
	.align	2, 0
	.globl	StopFieldMessage
	.type	 StopFieldMessage,function
	.thumb_func
StopFieldMessage:
	push	{lr}
	bl	DestroyTask_DrawFieldMessage
	ldr	r1, .L72
	mov	r0, #0x0
	strb	r0, [r1]
	pop	{r0}
	bx	r0
.L73:
	.align	2, 0
.L72:
	.word	sFieldMessageBoxMode
.Lfe17:
	.size	 StopFieldMessage,.Lfe17-StopFieldMessage
.text
	.align	2, 0

