@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.globl	gDifferentSaveFile
	.section ewram_data,"aw"
	.type	 gDifferentSaveFile,object
	.size	 gDifferentSaveFile,1
gDifferentSaveFile:
	.byte	0x0
	.globl	gEnableContestDebugging
	.type	 gEnableContestDebugging,object
	.size	 gEnableContestDebugging,1
gEnableContestDebugging:
	.byte	0x0
	.section .rodata
	.align	2, 0
	.type	 sContestWinnerPicDummy,object
	.size	 sContestWinnerPicDummy,32
sContestWinnerPicDummy:
	.space	11
	.byte	0xff
	.space	10
	.byte	0xff
	.space	7
	.space	2
.text
	.align	2, 0
	.globl	SetTrainerId
	.type	 SetTrainerId,function
	.thumb_func
SetTrainerId:
	strb	r0, [r1]
	lsr	r2, r0, #0x8
	strb	r2, [r1, #0x1]
	lsr	r2, r0, #0x10
	strb	r2, [r1, #0x2]
	lsr	r0, r0, #0x18
	strb	r0, [r1, #0x3]
	bx	lr
.Lfe1:
	.size	 SetTrainerId,.Lfe1-SetTrainerId
	.align	2, 0
	.globl	GetTrainerId
	.type	 GetTrainerId,function
	.thumb_func
GetTrainerId:
	add	r2, r0, #0
	ldrb	r0, [r2, #0x3]
	lsl	r0, r0, #0x18
	ldrb	r1, [r2, #0x2]
	lsl	r1, r1, #0x10
	orr	r0, r0, r1
	ldrb	r1, [r2, #0x1]
	lsl	r1, r1, #0x8
	orr	r0, r0, r1
	ldrb	r1, [r2]
	orr	r0, r0, r1
	bx	lr
.Lfe2:
	.size	 GetTrainerId,.Lfe2-GetTrainerId
	.align	2, 0
	.globl	CopyTrainerId
	.type	 CopyTrainerId,function
	.thumb_func
CopyTrainerId:
	push	{r4, lr}
	add	r4, r0, #0
	add	r3, r1, #0
	mov	r2, #0x0
.L8:
	add	r0, r4, r2
	add	r1, r3, r2
	ldrb	r1, [r1]
	strb	r1, [r0]
	add	r2, r2, #0x1
	cmp	r2, #0x3
	ble	.L8	@cond_branch
	pop	{r4}
	pop	{r0}
	bx	r0
.Lfe3:
	.size	 CopyTrainerId,.Lfe3-CopyTrainerId
	.align	2, 0
	.type	 InitPlayerTrainerId,function
	.thumb_func
InitPlayerTrainerId:
	push	{r4, lr}
	bl	Random
	add	r4, r0, #0
	bl	GetGeneratedTrainerIdLower
	lsl	r4, r4, #0x10
	lsl	r0, r0, #0x10
	lsr	r0, r0, #0x10
	orr	r4, r4, r0
	ldr	r0, .L11
	ldr	r1, [r0]
	add	r1, r1, #0xa
	add	r0, r4, #0
	bl	SetTrainerId
	pop	{r4}
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	gSaveBlock2Ptr
.Lfe4:
	.size	 InitPlayerTrainerId,.Lfe4-InitPlayerTrainerId
	.align	2, 0
	.type	 SetDefaultOptions,function
	.thumb_func
SetDefaultOptions:
	ldr	r3, .L14
	ldr	r2, [r3]
	ldrb	r1, [r2, #0x14]
	mov	r0, #0x8
	neg	r0, r0
	and	r0, r0, r1
	mov	r1, #0x2
	orr	r0, r0, r1
	strb	r0, [r2, #0x14]
	ldr	r2, [r3]
	ldrb	r1, [r2, #0x14]
	mov	r0, #0x7
	and	r0, r0, r1
	strb	r0, [r2, #0x14]
	ldr	r2, [r3]
	ldrb	r1, [r2, #0x15]
	mov	r0, #0x4
	neg	r0, r0
	and	r0, r0, r1
	mov	r1, #0x1
	orr	r0, r0, r1
	strb	r0, [r2, #0x15]
	ldr	r2, [r3]
	ldrb	r1, [r2, #0x15]
	mov	r0, #0x5
	neg	r0, r0
	and	r0, r0, r1
	strb	r0, [r2, #0x15]
	ldr	r2, [r3]
	ldrb	r1, [r2, #0x15]
	mov	r0, #0x9
	neg	r0, r0
	and	r0, r0, r1
	strb	r0, [r2, #0x15]
	ldr	r2, [r3]
	ldrb	r1, [r2, #0x15]
	mov	r0, #0x11
	neg	r0, r0
	and	r0, r0, r1
	strb	r0, [r2, #0x15]
	bx	lr
.L15:
	.align	2, 0
.L14:
	.word	gSaveBlock2Ptr
.Lfe5:
	.size	 SetDefaultOptions,.Lfe5-SetDefaultOptions
	.align	2, 0
	.type	 ClearPokedexFlags,function
	.thumb_func
ClearPokedexFlags:
	push	{r4, lr}
	ldr	r1, .L17
	mov	r0, #0x0
	strb	r0, [r1]
	ldr	r4, .L17+0x4
	ldr	r0, [r4]
	ldr	r1, .L17+0x8
	add	r0, r0, r1
	mov	r1, #0x0
	mov	r2, #0xbc
	bl	memset
	ldr	r0, [r4]
	ldr	r1, .L17+0xc
	add	r0, r0, r1
	mov	r1, #0x0
	mov	r2, #0xbc
	bl	memset
	pop	{r4}
	pop	{r0}
	bx	r0
.L18:
	.align	2, 0
.L17:
	.word	gUnusedPokedexU8
	.word	gSaveBlock1Ptr
	.word	0x2f34
	.word	0x2e78
.Lfe6:
	.size	 ClearPokedexFlags,.Lfe6-ClearPokedexFlags
	.align	2, 0
	.globl	ClearAllContestWinnerPics
	.type	 ClearAllContestWinnerPics,function
	.thumb_func
ClearAllContestWinnerPics:
	push	{r4, r5, r6, r7, lr}
	bl	ClearContestWinnerPicsInContestHall
	mov	r2, #0x8
	ldr	r0, .L25
	mov	ip, r0
	ldr	r4, .L25+0x4
	ldr	r3, .L25+0x8
.L23:
	mov	r1, ip
	ldr	r0, [r1]
	lsl	r1, r2, #0x5
	add	r0, r0, r1
	add	r0, r0, r4
	add	r1, r3, #0
	ldmia	r1!, {r5, r6, r7}
	stmia	r0!, {r5, r6, r7}
	ldmia	r1!, {r5, r6, r7}
	stmia	r0!, {r5, r6, r7}
	ldmia	r1!, {r5, r6}
	stmia	r0!, {r5, r6}
	add	r2, r2, #0x1
	cmp	r2, #0xc
	ble	.L23	@cond_branch
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L26:
	.align	2, 0
.L25:
	.word	gSaveBlock1Ptr
	.word	0x2b10
	.word	sContestWinnerPicDummy
.Lfe7:
	.size	 ClearAllContestWinnerPics,.Lfe7-ClearAllContestWinnerPics
	.align	2, 0
	.type	 ClearFrontierRecord,function
	.thumb_func
ClearFrontierRecord:
	push	{r4, lr}
	add	sp, sp, #-0x4
	mov	r0, #0x0
	str	r0, [sp]
	ldr	r4, .L28
	ldr	r1, [r4]
	ldr	r0, .L28+0x4
	add	r1, r1, r0
	ldr	r2, .L28+0x8
	mov	r0, sp
	bl	CpuSet
	ldr	r0, [r4]
	ldr	r1, .L28+0xc
	add	r0, r0, r1
	mov	r1, #0xff
	strb	r1, [r0]
	ldr	r0, [r4]
	ldr	r1, .L28+0x10
	add	r0, r0, r1
	mov	r1, #0x1
	neg	r1, r1
	strb	r1, [r0]
	add	sp, sp, #0x4
	pop	{r4}
	pop	{r0}
	bx	r0
.L29:
	.align	2, 0
.L28:
	.word	gSaveBlock2Ptr
	.word	0x5d4
	.word	0x5000238
	.word	0xe69
	.word	0xe71
.Lfe8:
	.size	 ClearFrontierRecord,.Lfe8-ClearFrontierRecord
	.align	2, 0
	.type	 WarpToTruck,function
	.thumb_func
WarpToTruck:
	push	{lr}
	add	sp, sp, #-0x4
	mov	r0, #0x1
	neg	r0, r0
	str	r0, [sp]
	mov	r0, #0x19
	mov	r1, #0x28
	mov	r2, #0x5
	mov	r3, #0x5
	bl	SetWarpDestination
	bl	WarpIntoMap
	add	sp, sp, #0x4
	pop	{r0}
	bx	r0
.Lfe9:
	.size	 WarpToTruck,.Lfe9-WarpToTruck
	.align	2, 0
	.globl	Sav2_ClearSetDefault
	.type	 Sav2_ClearSetDefault,function
	.thumb_func
Sav2_ClearSetDefault:
	push	{lr}
	bl	ClearSav2
	bl	SetDefaultOptions
	pop	{r0}
	bx	r0
.Lfe10:
	.size	 Sav2_ClearSetDefault,.Lfe10-Sav2_ClearSetDefault
	.align	2, 0
	.globl	ResetMenuAndMonGlobals
	.type	 ResetMenuAndMonGlobals,function
	.thumb_func
ResetMenuAndMonGlobals:
	push	{lr}
	ldr	r1, .L33
	mov	r0, #0x0
	strb	r0, [r1]
	bl	ResetPokedexScrollPositions
	bl	ZeroPlayerPartyMons
	bl	ZeroEnemyPartyMons
	bl	ResetBagScrollPositions
	bl	ResetPokeblockScrollPositions
	pop	{r0}
	bx	r0
.L34:
	.align	2, 0
.L33:
	.word	gDifferentSaveFile
.Lfe11:
	.size	 ResetMenuAndMonGlobals,.Lfe11-ResetMenuAndMonGlobals
	.align	2, 0
	.globl	NewGameInitData
	.type	 NewGameInitData,function
	.thumb_func
NewGameInitData:
	push	{r4, r5, r6, lr}
	mov	r6, r8
	push	{r6}
	ldr	r0, .L38
	ldrh	r0, [r0]
	cmp	r0, #0
	beq	.L37	@cond_branch
	cmp	r0, #0x2
	bne	.L36	@cond_branch
.L37:
	bl	RtcReset
.L36:
	ldr	r1, .L38+0x4
	mov	r0, #0x1
	strb	r0, [r1]
	ldr	r6, .L38+0x8
	ldr	r0, [r6]
	mov	r4, #0x0
	str	r4, [r0, #0x44]
	bl	ZeroPlayerPartyMons
	bl	ZeroEnemyPartyMons
	bl	ResetPokedex
	bl	ClearFrontierRecord
	bl	ClearSav1
	bl	ClearMailData
	ldr	r0, [r6]
	strb	r4, [r0, #0x9]
	ldr	r0, [r6]
	str	r4, [r0, #0x40]
	bl	InitPlayerTrainerId
	bl	PlayTimeCounter_Reset
	bl	ClearPokedexFlags
	bl	InitEventData
	bl	ClearTVShowData
	bl	ResetGabbyAndTy
	bl	ClearSecretBases
	bl	ClearBerryTrees
	ldr	r0, .L38+0xc
	mov	r8, r0
	ldr	r0, [r0]
	mov	r1, #0x92
	lsl	r1, r1, #0x3
	add	r0, r0, r1
	ldr	r1, .L38+0x10
	bl	SetMoney
	mov	r0, #0x0
	bl	SetCoins
	bl	ResetLinkContestBoolean
	bl	ResetGameStats
	bl	ClearAllContestWinnerPics
	bl	ClearPlayerLinkBattleRecords
	bl	InitSeedotSizeRecord
	bl	InitLotadSizeRecord
	ldr	r0, .L38+0x14
	strb	r4, [r0]
	bl	ZeroPlayerPartyMons
	bl	ResetPokemonStorageSystem
	bl	ClearRoamerData
	bl	ClearRoamerLocationData
	bl	ClearBag
	bl	NewGameInitPCItems
	bl	ClearPokeblocks
	bl	ClearDecorationInventories
	bl	InitEasyChatPhrases
	bl	SetMauvilleOldMan
	bl	InitDewfordTrend
	bl	ResetFanClub
	bl	ResetLotteryCorner
	bl	WarpToTruck
	ldr	r0, .L38+0x18
	bl	ScriptContext2_RunNewScript
	bl	ResetMiniGamesResults
	bl	InitUnionRoomChatRegisteredTexts
	bl	InitLilycoveLady
	bl	ResetAllApprenticeData
	bl	ClearRankingHallRecords
	bl	InitMatchCallCounters
	bl	sub_801AFD8
	bl	WipeTrainerNameRecords
	bl	ResetTrainerHillResults
	bl	ResetContestLinkResults
	ldr	r0, [r6]
	ldr	r2, .L38+0x1c
	add	r0, r0, r2
	mov	r1, #0x0
	mov	r2, #0x61
	bl	memset
	mov	r1, r8
	ldr	r0, [r1]
	ldr	r2, .L38+0x20
	add	r1, r0, r2
	mov	r5, #0x0
	strh	r4, [r1]
	ldr	r2, .L38+0x24
	add	r1, r0, r2
	strh	r4, [r1]
	add	r2, r2, #0x2
	add	r1, r0, r2
	strh	r4, [r1]
	ldr	r1, .L38+0x28
	add	r0, r0, r1
	ldr	r2, .L38+0x2c
	mov	r1, #0x0
	bl	memset
	mov	r2, r8
	ldr	r0, [r2]
	ldr	r1, .L38+0x30
	add	r0, r0, r1
	strb	r5, [r0]
	ldr	r1, [r6]
	mov	r0, #0x4
	strh	r0, [r1, #0x28]
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L39:
	.align	2, 0
.L38:
	.word	gSaveFileStatus
	.word	gDifferentSaveFile
	.word	gSaveBlock2Ptr
	.word	gSaveBlock1Ptr
	.word	0xbb8
	.word	gPlayerPartyCount
	.word	EventScript_ResetAllMapFlags
	.word	0xeb4
	.word	0x496
	.word	0x361c
	.word	0x3164
	.word	0x4b7
	.word	0x361b
.Lfe12:
	.size	 NewGameInitData,.Lfe12-NewGameInitData
	.align	2, 0
	.type	 ResetMiniGamesResults,function
	.thumb_func
ResetMiniGamesResults:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-0x4
	mov	r0, sp
	mov	r5, #0x0
	strh	r5, [r0]
	ldr	r4, .L41
	ldr	r1, [r4]
	mov	r0, #0xc2
	lsl	r0, r0, #0x1
	add	r1, r1, r0
	ldr	r6, .L41+0x4
	mov	r0, sp
	add	r2, r6, #0
	bl	CpuSet
	ldr	r0, [r4]
	mov	r1, #0xc6
	lsl	r1, r1, #0x1
	add	r0, r0, r1
	mov	r1, #0x0
	bl	SetBerryPowder
	bl	ResetPokeJumpResults
	mov	r0, sp
	add	r0, r0, #0x2
	strh	r5, [r0]
	ldr	r1, [r4]
	mov	r2, #0xca
	lsl	r2, r2, #0x1
	add	r1, r1, r2
	add	r2, r6, #0
	bl	CpuSet
	add	sp, sp, #0x4
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L42:
	.align	2, 0
.L41:
	.word	gSaveBlock2Ptr
	.word	0x1000008
.Lfe13:
	.size	 ResetMiniGamesResults,.Lfe13-ResetMiniGamesResults
.text
	.align	2, 0

