@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	1, 0
	.type	 InfusedSpeciesIDs,object
	.size	 InfusedSpeciesIDs,2414
InfusedSpeciesIDs:
	.space	2414
	.align	1, 0
	.type	 VanillaSpeciesIDs,object
	.size	 VanillaSpeciesIDs,2414
VanillaSpeciesIDs:
	.space	2
	.short	0x1
	.short	0x2
	.short	0x3
	.short	0x4
	.short	0x5
	.short	0x6
	.short	0x7
	.short	0x8
	.short	0x9
	.short	0xa
	.short	0xb
	.short	0xc
	.short	0xd
	.short	0xe
	.short	0xf
	.short	0x10
	.short	0x11
	.short	0x12
	.short	0x13
	.short	0x14
	.short	0x15
	.short	0x16
	.short	0x17
	.short	0x18
	.short	0x19
	.short	0x1a
	.short	0x1b
	.short	0x1c
	.short	0x1d
	.short	0x1e
	.short	0x1f
	.short	0x20
	.short	0x21
	.short	0x22
	.short	0x23
	.short	0x24
	.short	0x25
	.short	0x26
	.short	0x27
	.short	0x28
	.short	0x29
	.short	0x2a
	.short	0x2b
	.short	0x2c
	.short	0x2d
	.short	0x2e
	.short	0x2f
	.short	0x30
	.short	0x31
	.short	0x32
	.short	0x33
	.short	0x34
	.short	0x35
	.short	0x36
	.short	0x37
	.short	0x38
	.short	0x39
	.short	0x3a
	.short	0x3b
	.short	0x3c
	.short	0x3d
	.short	0x3e
	.short	0x3f
	.short	0x40
	.short	0x41
	.short	0x42
	.short	0x43
	.short	0x44
	.short	0x45
	.short	0x46
	.short	0x47
	.short	0x48
	.short	0x49
	.short	0x4a
	.short	0x4b
	.short	0x4c
	.short	0x4d
	.short	0x4e
	.short	0x4f
	.short	0x50
	.short	0x51
	.short	0x52
	.short	0x53
	.short	0x54
	.short	0x55
	.short	0x56
	.short	0x57
	.short	0x58
	.short	0x59
	.short	0x5a
	.short	0x5b
	.short	0x5c
	.short	0x5d
	.short	0x5e
	.short	0x5f
	.short	0x60
	.short	0x61
	.short	0x62
	.short	0x63
	.short	0x64
	.short	0x65
	.short	0x66
	.short	0x67
	.short	0x68
	.short	0x69
	.short	0x6a
	.short	0x6b
	.short	0x6c
	.short	0x6d
	.short	0x6e
	.short	0x6f
	.short	0x70
	.short	0x71
	.short	0x72
	.short	0x73
	.short	0x74
	.short	0x75
	.short	0x76
	.short	0x77
	.short	0x78
	.short	0x79
	.short	0x7a
	.short	0x7b
	.short	0x7c
	.short	0x7d
	.short	0x7e
	.short	0x7f
	.short	0x80
	.short	0x81
	.short	0x82
	.short	0x83
	.short	0x84
	.short	0x85
	.short	0x86
	.short	0x87
	.short	0x88
	.short	0x89
	.short	0x8a
	.short	0x8b
	.short	0x8c
	.short	0x8d
	.short	0x8e
	.short	0x8f
	.short	0x90
	.short	0x91
	.short	0x92
	.short	0x93
	.short	0x94
	.short	0x95
	.short	0x96
	.short	0x97
	.short	0x98
	.short	0x99
	.short	0x9a
	.short	0x9b
	.short	0x9c
	.short	0x9d
	.short	0x9e
	.short	0x9f
	.short	0xa0
	.short	0xa1
	.short	0xa2
	.short	0xa3
	.short	0xa4
	.short	0xa5
	.short	0xa6
	.short	0xa7
	.short	0xa8
	.short	0xa9
	.short	0xaa
	.short	0xab
	.short	0xac
	.short	0xad
	.short	0xae
	.short	0xaf
	.short	0xb0
	.short	0xb1
	.short	0xb2
	.short	0xb3
	.short	0xb4
	.short	0xb5
	.short	0xb6
	.short	0xb7
	.short	0xb8
	.short	0xb9
	.short	0xba
	.short	0xbb
	.short	0xbc
	.short	0xbd
	.short	0xbe
	.short	0xbf
	.short	0xc0
	.short	0xc1
	.short	0xc2
	.short	0xc3
	.short	0xc4
	.short	0xc5
	.short	0xc6
	.short	0xc7
	.short	0xc8
	.short	0xc9
	.short	0xca
	.short	0xcb
	.short	0xcc
	.short	0xcd
	.short	0xce
	.short	0xcf
	.short	0xd0
	.short	0xd1
	.short	0xd2
	.short	0xd3
	.short	0xd4
	.short	0xd5
	.short	0xd6
	.short	0xd7
	.short	0xd8
	.short	0xd9
	.short	0xda
	.short	0xdb
	.short	0xdc
	.short	0xdd
	.short	0xde
	.short	0xdf
	.short	0xe0
	.short	0xe1
	.short	0xe2
	.short	0xe3
	.short	0xe4
	.short	0xe5
	.short	0xe6
	.short	0xe7
	.short	0xe8
	.short	0xe9
	.short	0xea
	.short	0xeb
	.short	0xec
	.short	0xed
	.short	0xee
	.short	0xef
	.short	0xf0
	.short	0xf1
	.short	0xf2
	.short	0xf3
	.short	0xf4
	.short	0xf5
	.short	0xf6
	.short	0xf7
	.short	0xf8
	.short	0xf9
	.short	0xfa
	.short	0xfb
	.short	0x115
	.short	0x116
	.short	0x117
	.short	0x118
	.short	0x119
	.short	0x11a
	.short	0x11b
	.short	0x11c
	.short	0x11d
	.short	0x11e
	.short	0x11f
	.short	0x120
	.short	0x121
	.short	0x122
	.short	0x123
	.short	0x124
	.short	0x125
	.short	0x126
	.short	0x127
	.short	0x128
	.short	0x129
	.short	0x12a
	.short	0x12b
	.short	0x12c
	.short	0x130
	.short	0x131
	.short	0x135
	.short	0x136
	.short	0x188
	.short	0x189
	.short	0x18a
	.short	0x137
	.short	0x138
	.short	0x132
	.short	0x133
	.short	0x16c
	.short	0x16d
	.short	0x16e
	.short	0x12d
	.short	0x12e
	.short	0x12f
	.short	0x172
	.short	0x173
	.short	0x174
	.short	0x14f
	.short	0x150
	.short	0x15e
	.short	0x140
	.short	0x13b
	.short	0x13c
	.short	0x142
	.short	0x163
	.short	0x17e
	.short	0x17f
	.short	0x180
	.short	0x164
	.short	0x165
	.short	0x151
	.short	0x152
	.short	0x161
	.short	0x162
	.short	0x182
	.short	0x183
	.short	0x16b
	.short	0x16f
	.short	0x170
	.short	0x14a
	.short	0x14b
	.short	0x139
	.short	0x13a
	.short	0x153
	.short	0x154
	.short	0x141
	.short	0x15f
	.short	0x160
	.short	0x134
	.short	0x14c
	.short	0x14d
	.short	0x14e
	.short	0x158
	.short	0x159
	.short	0x166
	.short	0x167
	.short	0x17c
	.short	0x17b
	.short	0x15c
	.short	0x15d
	.short	0x143
	.short	0x144
	.short	0x146
	.short	0x147
	.short	0x13e
	.short	0x13f
	.short	0x184
	.short	0x185
	.short	0x186
	.short	0x187
	.short	0x148
	.short	0x149
	.short	0x181
	.short	0x13d
	.short	0x179
	.short	0x17a
	.short	0x169
	.short	0x16a
	.short	0x171
	.short	0x19b
	.short	0x178
	.short	0x168
	.short	0x15a
	.short	0x15b
	.short	0x155
	.short	0x156
	.short	0x157
	.short	0x175
	.short	0x176
	.short	0x177
	.short	0x17d
	.short	0x145
	.short	0x18b
	.short	0x18c
	.short	0x18d
	.short	0x18e
	.short	0x18f
	.short	0x190
	.short	0x191
	.short	0x192
	.short	0x193
	.short	0x197
	.short	0x198
	.short	0x194
	.short	0x195
	.short	0x196
	.short	0x199
	.short	0x19a
	.space	1640
	.align	1, 0
	.type	 RyuSpeciesIDs,object
	.size	 RyuSpeciesIDs,2414
RyuSpeciesIDs:
	.space	2
	.short	0x1
	.short	0x2
	.short	0x3
	.short	0x4
	.short	0x5
	.short	0x6
	.short	0x7
	.short	0x8
	.short	0x9
	.short	0xa
	.short	0xb
	.short	0xc
	.short	0xd
	.short	0xe
	.short	0xf
	.short	0x10
	.short	0x11
	.short	0x12
	.short	0x13
	.short	0x14
	.short	0x15
	.short	0x16
	.short	0x17
	.short	0x18
	.short	0x19
	.short	0x1a
	.short	0x1b
	.short	0x1c
	.short	0x1d
	.short	0x1e
	.short	0x1f
	.short	0x20
	.short	0x21
	.short	0x22
	.short	0x23
	.short	0x24
	.short	0x25
	.short	0x26
	.short	0x27
	.short	0x28
	.short	0x29
	.short	0x2a
	.short	0x2b
	.short	0x2c
	.short	0x2d
	.short	0x2e
	.short	0x2f
	.short	0x30
	.short	0x31
	.short	0x32
	.short	0x33
	.short	0x34
	.short	0x35
	.short	0x36
	.short	0x37
	.short	0x38
	.short	0x39
	.short	0x3a
	.short	0x3b
	.short	0x3c
	.short	0x3d
	.short	0x3e
	.short	0x3f
	.short	0x40
	.short	0x41
	.short	0x42
	.short	0x43
	.short	0x44
	.short	0x45
	.short	0x46
	.short	0x47
	.short	0x48
	.short	0x49
	.short	0x4a
	.short	0x4b
	.short	0x4c
	.short	0x4d
	.short	0x4e
	.short	0x4f
	.short	0x50
	.short	0x51
	.short	0x52
	.short	0x53
	.short	0x54
	.short	0x55
	.short	0x56
	.short	0x57
	.short	0x58
	.short	0x59
	.short	0x5a
	.short	0x5b
	.short	0x5c
	.short	0x5d
	.short	0x5e
	.short	0x5f
	.short	0x60
	.short	0x61
	.short	0x62
	.short	0x63
	.short	0x64
	.short	0x65
	.short	0x66
	.short	0x67
	.short	0x68
	.short	0x69
	.short	0x6a
	.short	0x6b
	.short	0x6c
	.short	0x6d
	.short	0x6e
	.short	0x6f
	.short	0x70
	.short	0x71
	.short	0x72
	.short	0x73
	.short	0x74
	.short	0x75
	.short	0x76
	.short	0x77
	.short	0x78
	.short	0x79
	.short	0x7a
	.short	0x7b
	.short	0x7c
	.short	0x7d
	.short	0x7e
	.short	0x7f
	.short	0x80
	.short	0x81
	.short	0x82
	.short	0x83
	.short	0x84
	.short	0x85
	.short	0x86
	.short	0x87
	.short	0x88
	.short	0x89
	.short	0x8a
	.short	0x8b
	.short	0x8c
	.short	0x8d
	.short	0x8e
	.short	0x8f
	.short	0x90
	.short	0x91
	.short	0x92
	.short	0x93
	.short	0x94
	.short	0x95
	.short	0x96
	.short	0x97
	.short	0x98
	.short	0x99
	.short	0x9a
	.short	0x9b
	.short	0x9c
	.short	0x9d
	.short	0x9e
	.short	0x9f
	.short	0xa0
	.short	0xa1
	.short	0xa2
	.short	0xa3
	.short	0xa4
	.short	0xa5
	.short	0xa6
	.short	0xa7
	.short	0xa8
	.short	0xa9
	.short	0xaa
	.short	0xab
	.short	0xac
	.short	0xad
	.short	0xae
	.short	0xaf
	.short	0xb0
	.short	0xb1
	.short	0xb2
	.short	0xb3
	.short	0xb4
	.short	0xb5
	.short	0xb6
	.short	0xb7
	.short	0xb8
	.short	0xb9
	.short	0xba
	.short	0xbb
	.short	0xbc
	.short	0xbd
	.short	0xbe
	.short	0xbf
	.short	0xc0
	.short	0xc1
	.short	0xc2
	.short	0xc3
	.short	0xc4
	.short	0xc5
	.short	0xc6
	.short	0xc7
	.short	0xc8
	.short	0xc9
	.short	0xca
	.short	0xcb
	.short	0xcc
	.short	0xcd
	.short	0xce
	.short	0xcf
	.short	0xd0
	.short	0xd1
	.short	0xd2
	.short	0xd3
	.short	0xd4
	.short	0xd5
	.short	0xd6
	.short	0xd7
	.short	0xd8
	.short	0xd9
	.short	0xda
	.short	0xdb
	.short	0xdc
	.short	0xdd
	.short	0xde
	.short	0xdf
	.short	0xe0
	.short	0xe1
	.short	0xe2
	.short	0xe3
	.short	0xe4
	.short	0xe5
	.short	0xe6
	.short	0xe7
	.short	0xe8
	.short	0xe9
	.short	0xea
	.short	0xeb
	.short	0xec
	.short	0xed
	.short	0xee
	.short	0xef
	.short	0xf0
	.short	0xf1
	.short	0xf2
	.short	0xf3
	.short	0xf4
	.short	0xf5
	.short	0xf6
	.short	0xf7
	.short	0xf8
	.short	0xf9
	.short	0xfa
	.short	0xfb
	.short	0xfc
	.short	0xfd
	.short	0xfe
	.short	0xff
	.short	0x100
	.short	0x101
	.short	0x102
	.short	0x103
	.short	0x104
	.short	0x105
	.short	0x106
	.short	0x107
	.short	0x108
	.short	0x109
	.short	0x10a
	.short	0x10b
	.short	0x10c
	.short	0x10d
	.short	0x10e
	.short	0x10f
	.short	0x110
	.short	0x111
	.short	0x112
	.short	0x113
	.short	0x114
	.short	0x115
	.short	0x116
	.short	0x117
	.short	0x118
	.short	0x119
	.short	0x11a
	.short	0x11b
	.short	0x11c
	.short	0x11d
	.short	0x11e
	.short	0x11f
	.short	0x120
	.short	0x121
	.short	0x122
	.short	0x123
	.short	0x124
	.short	0x125
	.short	0x126
	.short	0x127
	.short	0x128
	.short	0x129
	.short	0x12a
	.short	0x12b
	.short	0x12c
	.short	0x12d
	.short	0x12e
	.short	0x12f
	.short	0x130
	.short	0x131
	.short	0x132
	.short	0x133
	.short	0x134
	.short	0x135
	.short	0x136
	.short	0x137
	.short	0x138
	.short	0x139
	.short	0x13a
	.short	0x13b
	.short	0x13c
	.short	0x13d
	.short	0x13e
	.short	0x13f
	.short	0x140
	.short	0x141
	.short	0x142
	.short	0x143
	.short	0x144
	.short	0x145
	.short	0x146
	.short	0x147
	.short	0x148
	.short	0x149
	.short	0x14a
	.short	0x14b
	.short	0x14c
	.short	0x14d
	.short	0x14e
	.short	0x14f
	.short	0x150
	.short	0x151
	.short	0x152
	.short	0x153
	.short	0x154
	.short	0x155
	.short	0x156
	.short	0x157
	.short	0x158
	.short	0x159
	.short	0x15a
	.short	0x15b
	.short	0x15c
	.short	0x15d
	.short	0x15e
	.short	0x15f
	.short	0x160
	.short	0x161
	.short	0x162
	.short	0x163
	.short	0x164
	.short	0x165
	.space	2
	.short	0x167
	.short	0x168
	.short	0x169
	.short	0x16a
	.short	0x16b
	.short	0x16c
	.short	0x16d
	.short	0x16e
	.short	0x16f
	.short	0x170
	.short	0x171
	.short	0x172
	.short	0x173
	.short	0x174
	.short	0x175
	.short	0x176
	.short	0x177
	.short	0x178
	.short	0x179
	.short	0x17a
	.short	0x17b
	.short	0x17c
	.short	0x17d
	.short	0x17e
	.short	0x17f
	.short	0x180
	.short	0x181
	.short	0x182
	.short	0x183
	.short	0x184
	.short	0x185
	.short	0x186
	.short	0x187
	.short	0x188
	.short	0x189
	.short	0x18a
	.short	0x18b
	.short	0x18c
	.short	0x18d
	.short	0x18e
	.short	0x18f
	.short	0x190
	.short	0x191
	.short	0x192
	.short	0x193
	.short	0x194
	.short	0x195
	.short	0x196
	.short	0x197
	.short	0x198
	.short	0x199
	.short	0x19a
	.short	0x19b
	.short	0x19c
	.short	0x19d
	.short	0x19e
	.short	0x19f
	.short	0x1a0
	.short	0x1a1
	.short	0x1a2
	.short	0x1a3
	.short	0x1a4
	.short	0x1a5
	.short	0x1a6
	.short	0x1a7
	.short	0x1a8
	.short	0x1a9
	.short	0x1aa
	.short	0x1ab
	.short	0x1ac
	.short	0x1ad
	.short	0x1ae
	.short	0x1af
	.short	0x1b0
	.short	0x1b1
	.short	0x1b2
	.short	0x1b3
	.short	0x1b4
	.short	0x1b5
	.short	0x1b6
	.short	0x1b7
	.short	0x1b8
	.short	0x1b9
	.short	0x1ba
	.short	0x1bb
	.short	0x1bc
	.short	0x1bd
	.short	0x1be
	.short	0x1bf
	.short	0x1c0
	.short	0x1c1
	.short	0x1c2
	.short	0x1c3
	.short	0x1c4
	.short	0x1c5
	.short	0x1c6
	.short	0x1c7
	.short	0x1c8
	.short	0x1c9
	.short	0x1ca
	.short	0x1cb
	.short	0x1cc
	.short	0x1cd
	.short	0x1ce
	.short	0x1cf
	.short	0x1d0
	.short	0x1d1
	.short	0x1d2
	.short	0x1d3
	.short	0x1d4
	.short	0x1d5
	.short	0x1d6
	.short	0x1d7
	.short	0x1d8
	.short	0x1d9
	.short	0x1da
	.short	0x1db
	.short	0x1dc
	.short	0x1dd
	.short	0x1de
	.short	0x1df
	.short	0x1e0
	.short	0x1e1
	.short	0x1e2
	.short	0x1e3
	.short	0x1e4
	.short	0x1e5
	.short	0x1e6
	.short	0x1e7
	.short	0x1e8
	.short	0x1e9
	.short	0x1ea
	.short	0x1eb
	.short	0x1ec
	.short	0x1ed
	.short	0x1ee
	.short	0x1ef
	.short	0x1f0
	.short	0x1f1
	.short	0x1f2
	.short	0x1f3
	.short	0x1f4
	.short	0x1f5
	.short	0x1f6
	.short	0x1f7
	.short	0x1f8
	.short	0x1f9
	.short	0x1fa
	.short	0x1fb
	.short	0x1fc
	.short	0x1fd
	.short	0x1fe
	.short	0x1ff
	.short	0x200
	.short	0x201
	.short	0x202
	.short	0x203
	.short	0x204
	.short	0x205
	.short	0x206
	.short	0x207
	.short	0x208
	.short	0x209
	.short	0x20a
	.short	0x20b
	.short	0x20c
	.short	0x20d
	.short	0x20e
	.short	0x20f
	.short	0x210
	.short	0x211
	.short	0x212
	.short	0x213
	.short	0x214
	.short	0x215
	.short	0x216
	.short	0x217
	.short	0x218
	.short	0x219
	.short	0x21a
	.short	0x21b
	.short	0x21c
	.short	0x21d
	.short	0x21e
	.short	0x21f
	.short	0x220
	.short	0x221
	.short	0x222
	.short	0x223
	.short	0x224
	.short	0x225
	.short	0x226
	.short	0x227
	.short	0x228
	.short	0x229
	.short	0x22a
	.short	0x22b
	.short	0x22c
	.short	0x22d
	.short	0x22e
	.short	0x22f
	.short	0x230
	.short	0x231
	.short	0x232
	.short	0x233
	.short	0x234
	.short	0x235
	.short	0x236
	.short	0x237
	.short	0x238
	.short	0x239
	.short	0x23a
	.short	0x23b
	.short	0x23c
	.short	0x23d
	.short	0x23e
	.short	0x23f
	.short	0x240
	.short	0x241
	.short	0x242
	.short	0x243
	.short	0x244
	.short	0x245
	.short	0x246
	.short	0x247
	.short	0x248
	.short	0x249
	.short	0x24a
	.short	0x24b
	.short	0x24c
	.short	0x24d
	.short	0x24e
	.short	0x24f
	.short	0x250
	.short	0x251
	.short	0x252
	.short	0x253
	.short	0x254
	.short	0x255
	.short	0x256
	.short	0x257
	.short	0x258
	.short	0x259
	.short	0x25a
	.short	0x25b
	.short	0x25c
	.short	0x25d
	.short	0x25e
	.short	0x25f
	.short	0x260
	.short	0x261
	.short	0x262
	.short	0x263
	.short	0x264
	.short	0x265
	.short	0x266
	.short	0x267
	.short	0x268
	.short	0x269
	.short	0x26a
	.short	0x26b
	.short	0x26c
	.short	0x26d
	.short	0x26e
	.short	0x26f
	.short	0x270
	.short	0x271
	.short	0x272
	.short	0x273
	.short	0x274
	.short	0x275
	.short	0x276
	.short	0x277
	.short	0x278
	.short	0x279
	.short	0x27a
	.short	0x27b
	.short	0x27c
	.short	0x27d
	.short	0x27e
	.short	0x27f
	.short	0x280
	.short	0x281
	.short	0x282
	.short	0x283
	.short	0x284
	.short	0x285
	.short	0x286
	.short	0x287
	.short	0x288
	.short	0x289
	.short	0x28a
	.short	0x28b
	.short	0x28c
	.short	0x28d
	.short	0x28e
	.short	0x28f
	.short	0x290
	.short	0x291
	.short	0x292
	.short	0x293
	.short	0x294
	.short	0x295
	.short	0x296
	.short	0x297
	.short	0x298
	.short	0x299
	.short	0x29a
	.short	0x29b
	.short	0x29c
	.short	0x29d
	.short	0x29e
	.short	0x29f
	.short	0x2a0
	.short	0x2a1
	.short	0x2a2
	.short	0x2a3
	.short	0x2a4
	.short	0x2a5
	.short	0x2a6
	.short	0x2a7
	.short	0x2a8
	.short	0x2a9
	.short	0x2aa
	.short	0x2ab
	.short	0x2ac
	.short	0x2ad
	.short	0x2ae
	.short	0x2af
	.short	0x2b0
	.short	0x2b1
	.short	0x2b2
	.short	0x2b3
	.short	0x2b4
	.short	0x2b5
	.short	0x2b6
	.short	0x2b7
	.short	0x2b8
	.short	0x2b9
	.short	0x2ba
	.short	0x2bb
	.short	0x2bc
	.short	0x2bd
	.short	0x2be
	.short	0x2bf
	.short	0x2c0
	.short	0x2c1
	.short	0x2c2
	.short	0x2c3
	.short	0x2c4
	.short	0x2c5
	.short	0x2c6
	.short	0x2c7
	.short	0x2c8
	.short	0x2c9
	.short	0x2ca
	.short	0x2cb
	.short	0x2cc
	.short	0x2cd
	.short	0x2ce
	.short	0x2cf
	.short	0x2d0
	.short	0x2d1
	.short	0x2d2
	.short	0x2d3
	.short	0x2d4
	.short	0x2d5
	.short	0x2d6
	.short	0x2d7
	.short	0x2d8
	.short	0x2d9
	.short	0x2da
	.short	0x2db
	.short	0x2dc
	.short	0x2dd
	.short	0x2de
	.short	0x2df
	.short	0x2e0
	.short	0x2e1
	.short	0x2e2
	.short	0x2e3
	.short	0x2e4
	.short	0x2e5
	.short	0x2e6
	.short	0x2e7
	.short	0x2e8
	.short	0x2e9
	.short	0x2ea
	.short	0x2eb
	.short	0x2ec
	.short	0x2ed
	.short	0x2ee
	.short	0x2ef
	.short	0x2f0
	.short	0x2f1
	.short	0x2f2
	.short	0x2f3
	.short	0x2f4
	.short	0x2f5
	.short	0x2f6
	.short	0x2f7
	.short	0x2f8
	.short	0x2f9
	.short	0x2fa
	.short	0x2fb
	.short	0x2fc
	.short	0x2fd
	.short	0x2fe
	.short	0x2ff
	.short	0x300
	.short	0x301
	.short	0x302
	.short	0x303
	.short	0x304
	.short	0x305
	.short	0x306
	.short	0x307
	.short	0x308
	.short	0x309
	.short	0x30a
	.short	0x30b
	.short	0x30c
	.short	0x30d
	.short	0x30e
	.short	0x30f
	.short	0x310
	.short	0x311
	.short	0x312
	.short	0x313
	.short	0x314
	.short	0x315
	.short	0x316
	.short	0x317
	.short	0x318
	.short	0x319
	.short	0x31a
	.short	0x31b
	.short	0x31c
	.short	0x31d
	.short	0x31e
	.short	0x31f
	.short	0x320
	.short	0x321
	.short	0x322
	.short	0x323
	.short	0x324
	.short	0x325
	.short	0x326
	.short	0x327
	.short	0x328
	.short	0x329
	.space	178
	.short	0x32b
	.short	0x32c
	.short	0x32d
	.short	0x33b
	.short	0x357
	.short	0x34f
	.short	0x33f
	.short	0x34d
	.short	0x358
	.short	0x33c
	.short	0x337
	.short	0x33d
	.short	0x338
	.short	0x32e
	.short	0x32f
	.short	0x32a
	.short	0x34e
	.short	0x336
	.short	0x340
	.short	0x332
	.short	0x335
	.short	0x347
	.short	0x330
	.short	0x346
	.short	0x359
	.short	0x348
	.short	0x341
	.short	0x333
	.short	0x331
	.short	0x342
	.short	0x34c
	.short	0x354
	.short	0x349
	.short	0x334
	.short	0x33e
	.short	0x350
	.short	0x356
	.short	0x352
	.short	0x345
	.short	0x344
	.short	0x355
	.short	0x343
	.short	0x339
	.short	0x33a
	.short	0x34a
	.short	0x34b
	.short	0x351
	.short	0x353
	.short	0x378
	.short	0x379
	.short	0x366
	.short	0x367
	.short	0x368
	.short	0x369
	.short	0x36a
	.short	0x36b
	.short	0x36c
	.short	0x36d
	.short	0x36e
	.short	0x36f
	.short	0x370
	.short	0x371
	.short	0x372
	.short	0x373
	.short	0x374
	.short	0x375
	.short	0x376
	.short	0x377
	.space	128
	.short	0x38a
	.short	0x38b
	.short	0x38c
	.short	0x35a
	.short	0x35b
	.short	0x35c
	.short	0x35d
	.space	6
	.short	0x35e
	.short	0x35f
	.short	0x360
	.short	0x361
	.short	0x362
	.short	0x37b
	.short	0x37a
	.space	36
	.short	0x37c
	.space	14
	.short	0x37d
	.short	0x37e
	.short	0x37f
	.short	0x364
	.short	0x363
	.space	2
	.short	0x380
	.space	94
	.short	0x365
	.short	0x381
	.space	14
	.short	0x388
	.space	4
	.short	0x389
	.short	0x382
	.space	8
	.short	0x386
	.short	0x387
	.space	48
	.short	0x383
	.space	12
	.short	0x385
	.space	54
	.align	2, 0
	.type	 DimensionalSpeciesIDs,object
DimensionalSpeciesIDs:
	.word	InfusedSpeciesIDs
	.word	VanillaSpeciesIDs
	.word	RyuSpeciesIDs
	.size	 DimensionalSpeciesIDs,12
	.type	 gUDTradeText_InfusedDimension,object
gUDTradeText_InfusedDimension:
	.byte	0xc3
	.byte	0xe2
	.byte	0xda
	.byte	0xe9
	.byte	0xe7
	.byte	0xd9
	.byte	0xd8
	.byte	0x0
	.byte	0xbe
	.byte	0xdd
	.byte	0xe1
	.byte	0xd9
	.byte	0xe2
	.byte	0xe7
	.byte	0xdd
	.byte	0xe3
	.byte	0xe2
	.byte	0xff
	.size	 gUDTradeText_InfusedDimension,18
	.type	 gUDTradeText_VanillaDimension,object
gUDTradeText_VanillaDimension:
	.byte	0xd0
	.byte	0xd5
	.byte	0xe2
	.byte	0xdd
	.byte	0xe0
	.byte	0xe0
	.byte	0xd5
	.byte	0x0
	.byte	0xbe
	.byte	0xdd
	.byte	0xe1
	.byte	0xd9
	.byte	0xe2
	.byte	0xe7
	.byte	0xdd
	.byte	0xe3
	.byte	0xe2
	.byte	0xff
	.size	 gUDTradeText_VanillaDimension,18
	.type	 gUDTradeText_RyuDimension,object
gUDTradeText_RyuDimension:
	.byte	0xcc
	.byte	0xed
	.byte	0xe9
	.byte	0x0
	.byte	0xbe
	.byte	0xdd
	.byte	0xe1
	.byte	0xd9
	.byte	0xe2
	.byte	0xe7
	.byte	0xdd
	.byte	0xe3
	.byte	0xe2
	.byte	0xff
	.size	 gUDTradeText_RyuDimension,14
	.type	 gUDTradeText_Cancel,object
gUDTradeText_Cancel:
	.byte	0xbd
	.byte	0xd5
	.byte	0xe2
	.byte	0xd7
	.byte	0xd9
	.byte	0xe0
	.byte	0xff
	.size	 gUDTradeText_Cancel,7
	.align	2, 0
	.type	 sUDTradeMenu_Items_Main,object
sUDTradeMenu_Items_Main:
	.word	gUDTradeText_InfusedDimension
	.word	0x0
	.word	gUDTradeText_VanillaDimension
	.word	0x1
	.word	gUDTradeText_RyuDimension
	.word	0x2
	.word	gUDTradeText_Cancel
	.word	0x3
	.size	 sUDTradeMenu_Items_Main,32
	.align	2, 0
	.type	 sUDTradeMenu_Actions_Main,object
sUDTradeMenu_Actions_Main:
	.word	UDTradeAction_InfusedDimension
	.word	UDTradeAction_VanillaDimension
	.word	UDTradeAction_RyuDimension
	.word	UDTradeAction_Cancel
	.size	 sUDTradeMenu_Actions_Main,16
	.align	2, 0
	.type	 sUDTradeMenuWindowTemplate,object
	.size	 sUDTradeMenuWindowTemplate,8
sUDTradeMenuWindowTemplate:
	.byte	0x0
	.byte	0x1
	.byte	0x1
	.byte	0xd
	.byte	0x8
	.byte	0xf
	.short	0x1
	.align	2, 0
	.type	 sUDTradeMenu_ListTemplate_Main,object
	.size	 sUDTradeMenu_ListTemplate_Main,24
sUDTradeMenu_ListTemplate_Main:
	.word	sUDTradeMenu_Items_Main
	.word	ListMenuDefaultCursorMoveFunc
	.space	4
	.short	0x4
	.space	10
.text
	.align	2, 0
	.globl	UDTrade_ShowMainMenu
	.type	 UDTrade_ShowMainMenu,function
	.thumb_func
UDTrade_ShowMainMenu:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-0xc
	ldr	r0, .L3
	ldr	r3, .L3+0x4
	mov	r2, sp
	add	r1, r3, #0
	add	r1, r1, #0xc
	ldmia	r1!, {r4, r5, r6}
	stmia	r2!, {r4, r5, r6}
	ldr	r1, [r3]
	ldr	r2, [r3, #0x4]
	ldr	r3, [r3, #0x8]
	bl	UDTrade_ShowMenu
	add	sp, sp, #0xc
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	UDTradeTask_HandleMenuInput_Main
	.word	sUDTradeMenu_ListTemplate_Main
.Lfe1:
	.size	 UDTrade_ShowMainMenu,.Lfe1-UDTrade_ShowMainMenu
	.align	2, 0
	.type	 UDTrade_ShowMenu,function
	.thumb_func
UDTrade_ShowMenu:
	sub	sp, sp, #0xc
	push	{r4, r5, r6, lr}
	mov	r6, r8
	push	{r6}
	add	sp, sp, #-0x18
	mov	r8, r0
	str	r1, [sp, #0x2c]
	str	r2, [sp, #0x30]
	str	r3, [sp, #0x34]
	bl	HideMapNamePopUpWindow
	bl	LoadMessageBoxAndBorderGfx
	ldr	r0, .L6
	bl	AddWindow
	add	r5, r0, #0
	lsl	r5, r5, #0x18
	lsr	r5, r5, #0x18
	add	r0, r5, #0
	mov	r1, #0x0
	bl	DrawStdWindowFrame
	mov	r1, sp
	add	r0, sp, #0x2c
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	mov	r1, sp
	mov	r2, #0x0
	mov	r0, #0x4
	strh	r0, [r1, #0xe]
	mov	r0, sp
	strb	r5, [r0, #0x10]
	strb	r2, [r0, #0x11]
	mov	r0, #0x8
	strb	r0, [r1, #0x12]
	mov	r0, sp
	strb	r2, [r0, #0x13]
	mov	r3, sp
	ldrb	r1, [r3, #0x14]
	mov	r2, #0x10
	neg	r2, r2
	add	r0, r2, #0
	and	r0, r0, r1
	mov	r4, #0x1
	orr	r0, r0, r4
	strb	r0, [r3, #0x14]
	mov	r6, #0xf
	and	r0, r0, r6
	mov	r1, #0x20
	orr	r0, r0, r1
	strb	r0, [r3, #0x14]
	mov	r1, sp
	ldrb	r0, [r1, #0x15]
	and	r2, r2, r0
	orr	r2, r2, r4
	strb	r2, [r1, #0x15]
	and	r2, r2, r6
	mov	r0, #0x30
	orr	r2, r2, r0
	strb	r2, [r1, #0x15]
	mov	r2, sp
	ldrb	r0, [r2, #0x16]
	mov	r1, #0x8
	neg	r1, r1
	and	r1, r1, r0
	orr	r1, r1, r4
	strb	r1, [r2, #0x16]
	mov	r0, #0x39
	neg	r0, r0
	and	r0, r0, r1
	strb	r0, [r2, #0x16]
	mov	r1, sp
	mov	r3, #0x3f
	and	r0, r0, r3
	strb	r0, [r1, #0x16]
	ldrb	r1, [r2, #0x17]
	mov	r0, #0x40
	neg	r0, r0
	and	r0, r0, r1
	orr	r0, r0, r4
	strb	r0, [r2, #0x17]
	mov	r1, sp
	and	r0, r0, r3
	strb	r0, [r1, #0x17]
	mov	r0, sp
	mov	r1, #0x0
	mov	r2, #0x0
	bl	ListMenuInit
	add	r4, r0, #0
	lsl	r4, r4, #0x18
	lsr	r4, r4, #0x18
	add	r0, r5, #0
	mov	r1, #0x3
	bl	CopyWindowToVram
	mov	r0, r8
	mov	r1, #0x3
	bl	CreateTask
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r2, .L6+0x4
	lsl	r1, r0, #0x2
	add	r1, r1, r0
	lsl	r1, r1, #0x3
	add	r1, r1, r2
	strh	r4, [r1, #0x8]
	strh	r5, [r1, #0xa]
	add	sp, sp, #0x18
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6}
	pop	{r3}
	add	sp, sp, #0xc
	bx	r3
.L7:
	.align	2, 0
.L6:
	.word	sUDTradeMenuWindowTemplate
	.word	gTasks
.Lfe2:
	.size	 UDTrade_ShowMenu,.Lfe2-UDTrade_ShowMenu
	.align	2, 0
	.type	 UDTrade_DestroyMenu,function
	.thumb_func
UDTrade_DestroyMenu:
	push	{r4, r5, lr}
	add	r5, r0, #0
	lsl	r5, r5, #0x18
	lsr	r5, r5, #0x18
	ldr	r0, .L9
	lsl	r4, r5, #0x2
	add	r4, r4, r5
	lsl	r4, r4, #0x3
	add	r4, r4, r0
	ldrb	r0, [r4, #0x8]
	mov	r1, #0x0
	mov	r2, #0x0
	bl	DestroyListMenuTask
	ldrb	r0, [r4, #0xa]
	mov	r1, #0x1
	bl	ClearStdWindowAndFrame
	ldrb	r0, [r4, #0xa]
	bl	RemoveWindow
	add	r0, r5, #0
	bl	DestroyTask
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	gTasks
.Lfe3:
	.size	 UDTrade_DestroyMenu,.Lfe3-UDTrade_DestroyMenu
	.align	2, 0
	.type	 UDTradeAction_Cancel,function
	.thumb_func
UDTradeAction_Cancel:
	push	{r4, lr}
	add	r4, r0, #0
	lsl	r4, r4, #0x18
	lsr	r4, r4, #0x18
	ldr	r0, .L12
	mov	r1, #0x0
	bl	VarSet
	add	r0, r4, #0
	bl	UDTrade_DestroyMenu
	bl	ScriptContext2_Enable
	ldr	r0, .L12+0x4
	bl	ScriptContext1_SetupScript
	pop	{r4}
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	0x40ff
	.word	CableClub_EventScript_AbortLink
.Lfe4:
	.size	 UDTradeAction_Cancel,.Lfe4-UDTradeAction_Cancel
	.align	2, 0
	.type	 UDTradeAction_DestroyExtraWindow,function
	.thumb_func
UDTradeAction_DestroyExtraWindow:
	push	{r4, r5, lr}
	add	r5, r0, #0
	lsl	r5, r5, #0x18
	lsr	r5, r5, #0x18
	ldr	r0, .L15
	lsl	r4, r5, #0x2
	add	r4, r4, r5
	lsl	r4, r4, #0x3
	add	r4, r4, r0
	ldrb	r0, [r4, #0xa]
	mov	r1, #0x1
	bl	ClearStdWindowAndFrame
	ldrb	r0, [r4, #0xa]
	bl	RemoveWindow
	ldrb	r0, [r4, #0xc]
	mov	r1, #0x1
	bl	ClearStdWindowAndFrame
	ldrb	r0, [r4, #0xc]
	bl	RemoveWindow
	add	r0, r5, #0
	bl	DestroyTask
	bl	EnableBothScriptContexts
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L16:
	.align	2, 0
.L15:
	.word	gTasks
.Lfe5:
	.size	 UDTradeAction_DestroyExtraWindow,.Lfe5-UDTradeAction_DestroyExtraWindow
	.align	2, 0
	.type	 UDTradeTask_HandleMenuInput_Main,function
	.thumb_func
UDTradeTask_HandleMenuInput_Main:
	push	{r4, r5, r6, lr}
	lsl	r0, r0, #0x18
	lsr	r4, r0, #0x18
	add	r6, r4, #0
	ldr	r1, .L22
	lsl	r0, r4, #0x2
	add	r0, r0, r4
	lsl	r0, r0, #0x3
	add	r0, r0, r1
	ldrb	r0, [r0, #0x8]
	bl	ListMenu_ProcessInput
	add	r5, r0, #0
	ldr	r0, .L22+0x4
	ldrh	r1, [r0, #0x2e]
	mov	r0, #0x1
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L18	@cond_branch
	mov	r0, #0x5
	bl	PlaySE
	ldr	r1, .L22+0x8
	lsl	r0, r5, #0x2
	add	r0, r0, r1
	ldr	r1, [r0]
	cmp	r1, #0
	beq	.L20	@cond_branch
	add	r0, r4, #0
	bl	_call_via_r1
	b	.L20
.L23:
	.align	2, 0
.L22:
	.word	gTasks
	.word	gMain
	.word	sUDTradeMenu_Actions_Main
.L18:
	mov	r0, #0x2
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L20	@cond_branch
	mov	r0, #0x5
	bl	PlaySE
	add	r0, r6, #0
	bl	UDTrade_DestroyMenu
	bl	ScriptContext2_Enable
	ldr	r0, .L24
	bl	ScriptContext1_SetupScript
.L20:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L25:
	.align	2, 0
.L24:
	.word	CableClub_EventScript_AbortLink
.Lfe6:
	.size	 UDTradeTask_HandleMenuInput_Main,.Lfe6-UDTradeTask_HandleMenuInput_Main
	.align	2, 0
	.globl	GetDimensionSpeciesFromLocalSpecies
	.type	 GetDimensionSpeciesFromLocalSpecies,function
	.thumb_func
GetDimensionSpeciesFromLocalSpecies:
	push	{lr}
	lsl	r0, r0, #0x10
	lsr	r2, r0, #0x10
	lsl	r1, r1, #0x18
	lsr	r3, r1, #0x18
	cmp	r3, #0
	beq	.L31	@cond_branch
	ldr	r0, .L32
	cmp	r2, r0
	bhi	.L31	@cond_branch
	ldr	r1, .L32+0x4
	lsl	r0, r3, #0x2
	add	r0, r0, r1
	ldr	r1, [r0]
	cmp	r1, #0
	bne	.L29	@cond_branch
.L31:
	add	r0, r2, #0
	b	.L30
.L33:
	.align	2, 0
.L32:
	.word	0x4b7
	.word	DimensionalSpeciesIDs
.L29:
	lsl	r0, r2, #0x1
	add	r0, r0, r1
	ldrh	r0, [r0]
.L30:
	pop	{r1}
	bx	r1
.Lfe7:
	.size	 GetDimensionSpeciesFromLocalSpecies,.Lfe7-GetDimensionSpeciesFromLocalSpecies
	.align	2, 0
	.globl	GetLocalSpeciesFromDimensionSpecies
	.type	 GetLocalSpeciesFromDimensionSpecies,function
	.thumb_func
GetLocalSpeciesFromDimensionSpecies:
	push	{r4, lr}
	lsl	r0, r0, #0x10
	lsr	r3, r0, #0x10
	lsl	r1, r1, #0x18
	lsr	r0, r1, #0x18
	cmp	r0, #0
	bne	.L35	@cond_branch
	add	r0, r3, #0
	b	.L43
.L35:
	ldr	r4, .L46
	cmp	r3, r4
	bls	.L36	@cond_branch
	b	.L45
.L47:
	.align	2, 0
.L46:
	.word	0x4b6
.L44:
	add	r0, r2, #0
	b	.L43
.L36:
	mov	r2, #0x0
	lsl	r0, r0, #0x2
	ldr	r1, .L48
	add	r0, r0, r1
	ldr	r1, [r0]
.L40:
	lsl	r0, r2, #0x1
	add	r0, r0, r1
	ldrh	r0, [r0]
	cmp	r0, r3
	beq	.L44	@cond_branch
	add	r0, r2, #0x1
	lsl	r0, r0, #0x10
	lsr	r2, r0, #0x10
	cmp	r2, r4
	bls	.L40	@cond_branch
.L45:
	mov	r0, #0x0
.L43:
	pop	{r4}
	pop	{r1}
	bx	r1
.L49:
	.align	2, 0
.L48:
	.word	DimensionalSpeciesIDs
.Lfe8:
	.size	 GetLocalSpeciesFromDimensionSpecies,.Lfe8-GetLocalSpeciesFromDimensionSpecies
	.align	2, 0
	.globl	CalculateTradeEnemyPartyCount
	.type	 CalculateTradeEnemyPartyCount,function
	.thumb_func
CalculateTradeEnemyPartyCount:
	push	{r4, lr}
	ldr	r0, .L56
	mov	r1, #0x0
	strb	r1, [r0]
	b	.L51
.L57:
	.align	2, 0
.L56:
	.word	gEnemyPartyCount
.L53:
	ldrb	r0, [r4]
	add	r0, r0, #0x1
	strb	r0, [r4]
	add	r0, r4, #0
.L51:
	add	r4, r0, #0
	ldrb	r0, [r4]
	cmp	r0, #0x5
	bhi	.L52	@cond_branch
	add	r1, r0, #0
	mov	r0, #0x64
	mul	r0, r0, r1
	ldr	r1, .L58
	add	r0, r0, r1
	mov	r1, #0x38
	mov	r2, #0x0
	bl	GetMonData
	cmp	r0, #0
	bne	.L53	@cond_branch
.L52:
	ldrb	r0, [r4]
	pop	{r4}
	pop	{r1}
	bx	r1
.L59:
	.align	2, 0
.L58:
	.word	gEnemyParty
.Lfe9:
	.size	 CalculateTradeEnemyPartyCount,.Lfe9-CalculateTradeEnemyPartyCount
	.align	2, 0
	.type	 ValidateDimension,function
	.thumb_func
ValidateDimension:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	add	sp, sp, #-0xc
	lsl	r0, r0, #0x18
	lsr	r7, r0, #0x18
	ldr	r0, .L67
	bl	VarGet
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	mov	r5, #0x0
	ldr	r0, .L67+0x4
	ldrb	r0, [r0]
	cmp	r5, r0
	bcs	.L62	@cond_branch
	ldr	r1, .L67+0x8
	lsl	r0, r6, #0x3
	add	r0, r0, r1
	mov	r8, r0
.L64:
	mov	r0, #0x64
	mov	r1, r5
	mul	r1, r1, r0
	ldr	r0, .L67+0xc
	add	r4, r1, r0
	add	r0, r4, #0
	mov	r1, #0xb
	bl	GetMonData
	lsl	r0, r0, #0x10
	lsr	r0, r0, #0x10
	add	r1, r6, #0
	bl	GetDimensionSpeciesFromLocalSpecies
	lsl	r0, r0, #0x10
	cmp	r0, #0
	bne	.L63	@cond_branch
	add	r0, r4, #0
	mov	r1, #0x2
	mov	r2, sp
	bl	GetMonData
	ldr	r0, .L67+0x10
	mov	r1, sp
	bl	StringCopy
	mov	r0, r8
	ldr	r1, [r0]
	ldr	r0, .L67+0x14
	bl	StringCopy
	add	r0, r7, #0
	bl	UDTrade_DestroyMenu
	bl	ScriptContext2_Enable
	ldr	r0, .L67+0x18
	bl	ScriptContext1_SetupScript
	b	.L60
.L68:
	.align	2, 0
.L67:
	.word	0x40ff
	.word	gPlayerPartyCount
	.word	sUDTradeMenu_Items_Main
	.word	gPlayerParty
	.word	gStringVar1
	.word	gStringVar2
	.word	UDTrade_EventScript_SpeciesNotAllowed
.L63:
	add	r0, r5, #0x1
	lsl	r0, r0, #0x18
	lsr	r5, r0, #0x18
	ldr	r0, .L69
	ldrb	r0, [r0]
	cmp	r5, r0
	bcc	.L64	@cond_branch
.L62:
	add	r0, r7, #0
	bl	UDTrade_DestroyMenu
	bl	ScriptContext2_Enable
	ldr	r0, .L69+0x4
	bl	ScriptContext1_SetupScript
.L60:
	add	sp, sp, #0xc
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L70:
	.align	2, 0
.L69:
	.word	gPlayerPartyCount
	.word	CableClub_EventScript_TradeCenter
.Lfe10:
	.size	 ValidateDimension,.Lfe10-ValidateDimension
	.align	2, 0
	.type	 UDTradeAction_InfusedDimension,function
	.thumb_func
UDTradeAction_InfusedDimension:
	push	{r4, lr}
	add	r4, r0, #0
	lsl	r4, r4, #0x18
	lsr	r4, r4, #0x18
	mov	r0, #0x5
	bl	PlaySE
	ldr	r0, .L72
	mov	r1, #0x0
	bl	VarSet
	add	r0, r4, #0
	bl	ValidateDimension
	pop	{r4}
	pop	{r0}
	bx	r0
.L73:
	.align	2, 0
.L72:
	.word	0x40ff
.Lfe11:
	.size	 UDTradeAction_InfusedDimension,.Lfe11-UDTradeAction_InfusedDimension
	.align	2, 0
	.type	 UDTradeAction_VanillaDimension,function
	.thumb_func
UDTradeAction_VanillaDimension:
	push	{r4, lr}
	add	r4, r0, #0
	lsl	r4, r4, #0x18
	lsr	r4, r4, #0x18
	mov	r0, #0x5
	bl	PlaySE
	ldr	r0, .L75
	mov	r1, #0x1
	bl	VarSet
	add	r0, r4, #0
	bl	ValidateDimension
	pop	{r4}
	pop	{r0}
	bx	r0
.L76:
	.align	2, 0
.L75:
	.word	0x40ff
.Lfe12:
	.size	 UDTradeAction_VanillaDimension,.Lfe12-UDTradeAction_VanillaDimension
	.align	2, 0
	.type	 UDTradeAction_RyuDimension,function
	.thumb_func
UDTradeAction_RyuDimension:
	push	{r4, lr}
	add	r4, r0, #0
	lsl	r4, r4, #0x18
	lsr	r4, r4, #0x18
	mov	r0, #0x5
	bl	PlaySE
	ldr	r0, .L78
	mov	r1, #0x2
	bl	VarSet
	add	r0, r4, #0
	bl	ValidateDimension
	pop	{r4}
	pop	{r0}
	bx	r0
.L79:
	.align	2, 0
.L78:
	.word	0x40ff
.Lfe13:
	.size	 UDTradeAction_RyuDimension,.Lfe13-UDTradeAction_RyuDimension
.text
	.align	2, 0

